# Generated by Django 6.0.2 on 2026-02-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumupload',
            name='current_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='curriculumupload',
            name='extracted_text_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='curriculumupload',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculumupload',
            name='teacher_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='curriculumupload',
            name='units_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curriculumupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('review', 'Review'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
