# Generated by Django 6.0.2 on 2026-02-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_curriculumupload_current_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumupload',
            name='steps_created',
            field=models.IntegerField(default=0),
        ),
    ]
