# Generated by Django 6.0.2 on 2026-02-24 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_lessonstep_curriculum_context_and_more'),
        ('dashboard', '0005_teachingmaterialupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingmaterialupload',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_materials', to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='teachingmaterialupload',
            name='curriculum_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_materials', to='dashboard.curriculumupload'),
        ),
    ]
