# Generated by Django 6.0.2 on 2026-02-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_teachingmaterialupload_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingmaterialupload',
            name='material_type',
            field=models.CharField(choices=[('textbook', 'Textbook'), ('reference', 'Reference'), ('worksheet', 'Worksheet'), ('notes', 'Notes'), ('question_bank', 'Question Bank / Exam Paper'), ('other', 'Other')], default='textbook', max_length=20),
        ),
    ]
