# Generated by Django 6.0.2 on 2026-02-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_teachingmaterialupload_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumupload',
            name='grade_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherclass',
            name='grade_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teachingmaterialupload',
            name='grade_level',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
