# Generated by Django 6.0.2 on 2026-02-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_add_figures_extracted_to_teachingmaterialupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingmaterialupload',
            name='figures_extracted',
            field=models.IntegerField(db_default=0, default=0),
        ),
    ]
