# Generated by Django 6.0.2 on 2026-03-02 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_alter_course_institution'),
        ('dashboard', '0013_allow_null_institution_teaching_material_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumupload',
            name='created_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.course'),
        ),
        migrations.AlterField(
            model_name='teachingmaterialupload',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_materials', to='curriculum.course'),
        ),
    ]
