# Generated by Django 6.0.2 on 2026-04-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_cascade_delete_uploads_with_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumupload',
            name='lesson_duration_minutes',
            field=models.PositiveIntegerField(default=20, help_text='Target lesson duration in minutes (controls steps and EOs per lesson)'),
        ),
    ]
