# Generated by Django 6.0.2 on 2026-05-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_feedback_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingmaterialupload',
            name='estimated_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='teachingmaterialupload',
            name='estimated_duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachingmaterialupload',
            name='job_execution_name',
            field=models.CharField(blank=True, db_default='', max_length=128),
        ),
        migrations.AddField(
            model_name='teachingmaterialupload',
            name='pages_processed',
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='teachingmaterialupload',
            name='pages_total',
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='teachingmaterialupload',
            name='phase',
            field=models.CharField(blank=True, db_default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='teachingmaterialupload',
            name='status',
            field=models.CharField(choices=[('pending_confirmation', 'Awaiting confirmation'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
