# Generated by Django 6.0.2 on 2026-06-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_curriculum_upload_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumupload',
            name='first_page',
            field=models.PositiveIntegerField(blank=True, help_text='1-based first page of the target grade within a multi-grade PDF. Blank = parse the whole document.', null=True),
        ),
        migrations.AddField(
            model_name='curriculumupload',
            name='last_page',
            field=models.PositiveIntegerField(blank=True, help_text='1-based last page (inclusive) of the target grade. Blank = read to the end of the document.', null=True),
        ),
    ]
