# Generated by Django 6.0.2 on 2026-02-25 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_move_branding_to_platformconfig'),
        ('llm', '0002_promptpack_content_generation_prompt_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promptpack',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='promptpack',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Null = platform-wide prompts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_packs', to='accounts.institution'),
        ),
    ]
