# Generated by Django 6.0.2 on 2026-02-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_make_promptpack_institution_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='purpose',
            field=models.CharField(choices=[('generation', 'Content Generation (Curriculum, Lessons)'), ('tutoring', 'Student Tutoring')], default='generation', max_length=20),
        ),
    ]
