# Generated by Django 6.0.2 on 2026-02-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0007_alter_modelconfig_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='api_key_encrypted',
            field=models.TextField(blank=True, default='', help_text='Fernet-encrypted API key (overrides env var when set)'),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT)'), ('google', 'Google (Gemini)'), ('azure_openai', 'Azure OpenAI'), ('local_ollama', 'Local (Ollama)')], default='anthropic', max_length=20),
        ),
    ]
