# Generated by Django 6.0.2 on 2026-02-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0008_modelconfig_api_key_encrypted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='purpose',
            field=models.CharField(choices=[('generation', 'Content Generation (Curriculum, Lessons)'), ('tutoring', 'Student Tutoring'), ('exit_tickets', 'Exit Ticket Generation'), ('skill_extraction', 'Skill Extraction'), ('image_generation', 'Image Generation')], default='generation', max_length=20),
        ),
    ]
