# Generated by Django 6.0.2 on 2026-04-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0009_add_image_generation_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileInferenceModel',
            fields=[
                ('id', models.CharField(help_text='Stable identifier, e.g. "qwen-3-5-2b-q4-k-m"', max_length=100, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=200)),
                ('family', models.CharField(choices=[('gemma_3n', 'Gemma 3n'), ('qwen_3_5', 'Qwen 3.5'), ('llama_3_2', 'Llama 3.2'), ('phi_3_5', 'Phi 3.5'), ('other', 'Other')], max_length=30)),
                ('size_mb', models.PositiveIntegerField(help_text='Approximate on-disk size at the chosen quantization.')),
                ('ram_required_mb', models.PositiveIntegerField(help_text='RAM headroom needed for inference.')),
                ('download_url', models.URLField(max_length=500)),
                ('checksum_sha256', models.CharField(blank=True, help_text='SHA-256 of the model file. Verified by the app post-download.', max_length=64)),
                ('license', models.CharField(default='Apache 2.0', help_text='License the weights are distributed under (e.g. "Apache 2.0", "Gemma").', max_length=80)),
                ('runtime', models.CharField(choices=[('llama_cpp', 'llama.cpp (GGUF)'), ('executorch', 'ExecuTorch'), ('mediapipe', 'MediaPipe LLM Inference'), ('mlx', 'MLX (iOS)')], max_length=30)),
                ('capabilities', models.JSONField(default=dict, help_text='{"text": true, "image": false, "audio": false, "video": false}')),
                ('chat_template', models.TextField(blank=True, default='', help_text='Jinja-like chat template the client renders before inference.')),
                ('system_prompt_style', models.CharField(choices=[('system_role', 'system role message'), ('prepend_user', 'prepend to first user message'), ('none', 'no system prompt')], default='system_role', max_length=30)),
                ('recommended_tier', models.CharField(choices=[('flagship', 'Flagship (iPhone 14+ / Pixel 7+)'), ('mid', 'Mid-range (~3yr-old phones)'), ('low', 'Low-end (older / entry-level)')], default='mid', max_length=20)),
                ('quality_scores', models.JSONField(blank=True, default=dict, help_text='{"math": 0.8, "science": 0.85, ...} from the M0 bake-off.')),
                ('is_active', models.BooleanField(default=True)),
                ('min_app_version', models.CharField(blank=True, help_text='Hide this model from app builds older than this.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mobile Inference Model',
                'ordering': ['recommended_tier', 'size_mb'],
            },
        ),
    ]
