# Generated by Django 6.0.2 on 2026-04-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0011_default_image_gen_to_openai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='purpose',
            field=models.CharField(choices=[('generation', 'Content Generation (Curriculum, Lessons)'), ('tutoring', 'Student Tutoring'), ('exit_tickets', 'Exit Ticket Generation'), ('skill_extraction', 'Skill Extraction'), ('image_generation', 'Image Generation'), ('help_assistant', 'In-app Help Assistant')], default='generation', max_length=20),
        ),
    ]
