# Generated by Django 6.0.2 on 2026-05-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0017_tutoring_to_sonnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='purpose',
            field=models.CharField(choices=[('generation', 'Content Generation (Curriculum, Lessons)'), ('tutoring', 'Student Tutoring'), ('exit_tickets', 'Exit Ticket Generation'), ('skill_extraction', 'Skill Extraction'), ('image_generation', 'Image Generation'), ('help_assistant', 'In-app Help Assistant'), ('judge', 'Post-response Judge'), ('regen', 'Tutor Response Regeneration')], default='generation', max_length=20),
        ),
    ]
