# Generated by Django 6.0.2 on 2026-05-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0024_alter_modelconfig_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='purpose',
            field=models.CharField(choices=[('generation', 'Content Generation (Curriculum, Lessons)'), ('tutoring', 'Student Tutoring'), ('exit_tickets', 'Exit Ticket Generation'), ('skill_extraction', 'Skill Extraction'), ('image_generation', 'Image Generation'), ('help_assistant', 'In-app Help Assistant'), ('judge', 'Post-response Judge'), ('regen', 'Tutor Response Regeneration'), ('student_sim', 'Synthetic Student (Simulator)'), ('content_judge_image_prompt', 'Content Judge — Image Prompt (PRE-gen)'), ('content_judge_factual_step', 'Content Judge — Factual (Lesson Step)'), ('content_judge_figure_alignment', 'Content Judge — Figure Alignment (POST-gen vision)'), ('content_judge_exit_question', 'Content Judge — Exit Ticket Question (MCQ)')], default='generation', max_length=40),
        ),
    ]
