# Generated by Django 6.0.2 on 2026-05-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0028_swap_runtime_to_gemini_3_1_flash_lite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='purpose',
            field=models.CharField(choices=[('generation', 'Content Generation (Curriculum, Lessons)'), ('tutoring', 'Student Tutoring'), ('exit_tickets', 'Exit Ticket Generation'), ('skill_extraction', 'Skill Extraction'), ('image_generation', 'Image Generation'), ('help_assistant', 'In-app Help Assistant'), ('judge', 'Post-response Judge'), ('judge_fallback', 'Post-response Judge — Tier 2 Fallback'), ('judge_fallback_2', 'Post-response Judge — Tier 3 Fallback'), ('regen', 'Tutor Response Regeneration'), ('student_sim', 'Synthetic Student (Simulator)'), ('content_judge_image_prompt', 'Content Judge — Image Prompt (PRE-gen)'), ('content_judge_factual_step', 'Content Judge — Factual (Lesson Step)'), ('content_judge_figure_alignment', 'Content Judge — Figure Alignment (POST-gen vision)'), ('content_judge_exit_question', 'Content Judge — Exit Ticket Question (MCQ)'), ('content_judge_pedagogy_step', 'Content Judge — Pedagogical Soundness (Lesson Step)'), ('content_judge_safety_content', 'Content Judge — Safety + Cultural Fit (Content)')], default='generation', max_length=40),
        ),
    ]
