# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0032_judge_to_gemini_2_5_flash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='provider',
            field=models.CharField(
                choices=[
                    ('anthropic', 'Anthropic (Claude)'),
                    ('openai', 'OpenAI (GPT)'),
                    ('google', 'Google (Gemini)'),
                    ('azure_openai', 'Azure OpenAI'),
                    ('local_ollama', 'Local (Ollama)'),
                    ('vertex_model_garden', 'Vertex Model Garden (MaaS)'),
                ],
                default='anthropic',
                max_length=20,
            ),
        ),
    ]
