"""Generated by scripts/build_playbook_translations.py — do not edit.

The contents rail for each TRANSLATED section, keyed by language then
slug. The English rail lives in _index.py; this is its counterpart for
the languages whose prose has been translated.

Anchors are the English ones by construction — a translated heading
keeps the id it was generated with, so every rail link and every
inbound deep link still resolves.
"""

HEADINGS_BY_LANGUAGE = {
    'fr': {
        'adoption-models': [
            ('the-offline-options-in-more-detail', 'Les options hors ligne en détail'),
            ('choosing-between-them', 'Choisir entre elles'),
        ],
        'data-sovereignty': [
            ('what-stays-where-you-put-it', 'Ce qui reste là où vous le placez'),
            ('what-leaves-and-why-no-setting-changes-it', "Ce qui sort, et pourquoi aucun réglage n'y change rien"),
            ('three-ways-to-close-the-gap', "Trois façons de combler l'écart"),
            ('compliance-features-already-in-the-platform', 'Fonctions de conformité déjà présentes dans la plateforme'),
        ],
        'evidence': [
            ('layer-1-the-runtime-judge', "Niveau 1 — L'évaluateur à l'exécution"),
            ('layer-2-turn-level-evaluation-against-a-rubric', 'Niveau 2 — Évaluation par tour selon une grille'),
            ('layer-3-session-level-pedagogical-evaluation', 'Niveau 3 — Évaluation pédagogique au niveau de la séance'),
            ('the-quality-gate-to-apply-before-a-cohort', 'Le contrôle qualité à appliquer avant une cohorte'),
        ],
        'executive-summary': [
            ('the-five-things-a-country-adapts', "Les cinq choses qu'un pays adapte"),
            ('the-one-decision-that-changes-everything-else', 'La décision qui conditionne toutes les autres'),
        ],
        'five-layers': [
            ('layer-1-language-and-register', 'Couche 1 — Langue et registre'),
            ('layer-2-curriculum', 'Couche 2 — Programme'),
            ('layer-3-local-context', 'Couche 3 — Contexte local'),
            ('layer-4-national-structures', 'Couche 4 — Structures nationales'),
            ('layer-5-infrastructure-and-data-residency', 'Couche 5 — Infrastructure et résidence des données'),
        ],
        'hosting': [
            ('choosing-a-path', 'Choisir un parcours'),
            ('path-a-one-server', 'Parcours A — un serveur'),
            ('path-b-your-own-aws-account', 'Parcours B — votre propre compte AWS'),
            ('the-two-offline-shapes', 'Les deux formats hors ligne'),
            ('when-something-is-wrong', 'Quand quelque chose ne va pas'),
            ('backup-and-restore', 'Sauvegarde et restauration'),
            ('logs', 'Journaux'),
        ],
        'teacher-training': [
            ('what-a-teacher-has-to-be-able-to-do-and-when', "Ce qu'un enseignant doit savoir faire, et quand"),
            ('who-trains-whom', 'Qui forme qui'),
            ('three-lines-of-support', 'Trois niveaux de soutien'),
            ('what-to-measure', "Ce qu'il faut mesurer"),
            ('failure-modes-specific-to-training', 'Modes de défaillance propres à la formation'),
        ],
        'what-is-adopted': [
            ('for-the-student', "Pour l'élève"),
            ('for-the-teacher', "Pour l'enseignant"),
            ('for-the-ministry', 'Pour le ministère'),
            ('the-content-pipeline', 'La chaîne de production du contenu'),
            ('the-quality-layer', 'La couche qualité'),
        ],
    },
    'pt_mz': {
        'adoption-models': [
            ('the-offline-options-in-more-detail', 'As opções offline em mais detalhe'),
            ('choosing-between-them', 'Escolher entre eles'),
        ],
        'data-sovereignty': [
            ('what-stays-where-you-put-it', 'O que fica onde o colocar'),
            ('what-leaves-and-why-no-setting-changes-it', 'O que sai, e porque nenhuma configuração o altera'),
            ('three-ways-to-close-the-gap', 'Três formas de fechar essa lacuna'),
            ('compliance-features-already-in-the-platform', 'Funcionalidades de conformidade já existentes na plataforma'),
        ],
        'evidence': [
            ('layer-1-the-runtime-judge', 'Nível 1 — O avaliador em execução'),
            ('layer-2-turn-level-evaluation-against-a-rubric', 'Nível 2 — Avaliação por turno segundo uma rubrica'),
            ('layer-3-session-level-pedagogical-evaluation', 'Nível 3 — Avaliação pedagógica ao nível da sessão'),
            ('the-quality-gate-to-apply-before-a-cohort', 'O critério de qualidade a aplicar antes de uma turma'),
        ],
        'executive-summary': [
            ('the-five-things-a-country-adapts', 'As cinco coisas que um país adapta'),
            ('the-one-decision-that-changes-everything-else', 'A decisão que altera todas as outras'),
        ],
        'five-layers': [
            ('layer-1-language-and-register', 'Camada 1 — Língua e registo'),
            ('layer-2-curriculum', 'Camada 2 — Currículo'),
            ('layer-3-local-context', 'Camada 3 — Contexto local'),
            ('layer-4-national-structures', 'Camada 4 — Estruturas nacionais'),
            ('layer-5-infrastructure-and-data-residency', 'Camada 5 — Infra-estrutura e residência dos dados'),
        ],
        'hosting': [
            ('choosing-a-path', 'Escolher um caminho'),
            ('path-a-one-server', 'Caminho A — um servidor'),
            ('path-b-your-own-aws-account', 'Caminho B — a sua própria conta AWS'),
            ('the-two-offline-shapes', 'Os dois formatos offline'),
            ('when-something-is-wrong', 'Quando algo corre mal'),
            ('backup-and-restore', 'Cópias de segurança e restauro'),
            ('logs', 'Registos'),
        ],
        'teacher-training': [
            ('what-a-teacher-has-to-be-able-to-do-and-when', 'O que um professor tem de saber fazer, e quando'),
            ('who-trains-whom', 'Quem forma quem'),
            ('three-lines-of-support', 'Três linhas de apoio'),
            ('what-to-measure', 'O que medir'),
            ('failure-modes-specific-to-training', 'Modos de falha próprios da formação'),
        ],
        'what-is-adopted': [
            ('for-the-student', 'Para o aluno'),
            ('for-the-teacher', 'Para o professor'),
            ('for-the-ministry', 'Para o ministério'),
            ('the-content-pipeline', 'O pipeline de conteúdos'),
            ('the-quality-layer', 'A camada de qualidade'),
        ],
    },
    'sw': {
        'adoption-models': [
            ('the-offline-options-in-more-detail', 'Chaguo za nje ya mtandao kwa undani zaidi'),
            ('choosing-between-them', 'Kuchagua kati yao'),
        ],
        'data-sovereignty': [
            ('what-stays-where-you-put-it', 'Kinachobaki pale unapokiweka'),
            ('what-leaves-and-why-no-setting-changes-it', 'Kinachotoka, na kwa nini hakuna mpangilio unaokibadilisha'),
            ('three-ways-to-close-the-gap', 'Njia tatu za kuziba pengo'),
            ('compliance-features-already-in-the-platform', 'Vipengele vya utiifu vilivyomo tayari katika jukwaa'),
        ],
        'evidence': [
            ('layer-1-the-runtime-judge', 'Tabaka la 1 — Jaji wa wakati halisi'),
            ('layer-2-turn-level-evaluation-against-a-rubric', 'Tabaka la 2 — Tathmini ya kila zamu dhidi ya kigezo'),
            ('layer-3-session-level-pedagogical-evaluation', 'Tabaka la 3 — Tathmini ya kimafunzo ya kipindi kizima'),
            ('the-quality-gate-to-apply-before-a-cohort', 'Lango la ubora la kutumia kabla ya kundi'),
        ],
        'executive-summary': [
            ('the-five-things-a-country-adapts', 'Mambo matano ambayo nchi huyaasili'),
            ('the-one-decision-that-changes-everything-else', 'Uamuzi mmoja unaobadilisha kila kitu kingine'),
        ],
        'five-layers': [
            ('layer-1-language-and-register', 'Tabaka la 1 — Lugha na mtindo'),
            ('layer-2-curriculum', 'Tabaka la 2 — Mtaala'),
            ('layer-3-local-context', 'Tabaka la 3 — Muktadha wa ndani'),
            ('layer-4-national-structures', 'Tabaka la 4 — Miundo ya kitaifa'),
            ('layer-5-infrastructure-and-data-residency', 'Tabaka la 5 — Miundombinu na mahali data inapokaa'),
        ],
        'hosting': [
            ('choosing-a-path', 'Kuchagua njia'),
            ('path-a-one-server', 'Njia A — seva moja'),
            ('path-b-your-own-aws-account', 'Njia B — akaunti yako mwenyewe ya AWS'),
            ('the-two-offline-shapes', 'Miundo miwili ya nje ya mtandao'),
            ('when-something-is-wrong', 'Kunapokuwa na tatizo'),
            ('backup-and-restore', 'Nakala rudufu na kurejesha'),
            ('logs', 'Kumbukumbu'),
        ],
        'teacher-training': [
            ('what-a-teacher-has-to-be-able-to-do-and-when', 'Mwalimu anapaswa kuweza kufanya nini, na lini'),
            ('who-trains-whom', 'Nani anamfundisha nani'),
            ('three-lines-of-support', 'Mistari mitatu ya msaada'),
            ('what-to-measure', 'Cha kupima'),
            ('failure-modes-specific-to-training', 'Namna za kushindwa mahususi kwa mafunzo'),
        ],
        'what-is-adopted': [
            ('for-the-student', 'Kwa mwanafunzi'),
            ('for-the-teacher', 'Kwa mwalimu'),
            ('for-the-ministry', 'Kwa wizara'),
            ('the-content-pipeline', 'Mfumo wa maudhui'),
            ('the-quality-layer', 'Tabaka la ubora'),
        ],
    },
}
