"""Generated by scripts/build_playbook_translations.py — do not edit.

The contents rail for each TRANSLATED section, keyed by language then
slug. The English rail lives in _index.py; this is its counterpart for
the languages whose prose has been translated.

Anchors are the English ones by construction — a translated heading
keeps the id it was generated with, so every rail link and every
inbound deep link still resolves.
"""

HEADINGS_BY_LANGUAGE = {
    'fr': {
        'adoption-models': [
            ('the-offline-options-in-more-detail', 'Les options hors ligne en détail'),
            ('choosing-between-them', 'Choisir entre elles'),
        ],
        'cost-sharing': [
            ('the-cost-lines-behave-differently-so-share-them-differently', 'Les postes de coût se comportent différemment : partagez-les différemment'),
            ('four-funding-models', 'Quatre modèles de financement'),
            ('making-the-recurring-line-small', 'Réduire le poste récurrent'),
            ('a-cost-per-student-figure-you-can-defend', 'Un coût par élève que vous pouvez défendre'),
            ('sustainability-is-not-only-financial', "La pérennité n'est pas seulement financière"),
            ('what-to-write-into-the-funding-agreement', "Ce qu'il faut inscrire dans l'accord de financement"),
        ],
        'costs': [
            ('fixed-infrastructure-a-country-owned-cloud-instance', 'Infrastructure fixe — une instance de nuage détenue par le pays'),
            ('variable-cost-the-model-and-it-dominates', "Coût variable — le modèle, et c'est lui qui domine"),
            ('levers-in-the-order-worth-pulling-them', "Les leviers, dans l'ordre où il vaut la peine de les actionner"),
            ('modelling-it-for-your-country', 'Le modéliser pour votre pays'),
        ],
        'curriculum-pipeline': [
            ('two-routes-in', "Deux voies d'entrée"),
            ('the-generation-pipeline', 'La chaîne de génération'),
            ('practical-notes', 'Remarques pratiques'),
        ],
        'data-sovereignty': [
            ('what-stays-where-you-put-it', 'Ce qui reste là où vous le placez'),
            ('what-leaves-and-why-no-setting-changes-it', "Ce qui sort, et pourquoi aucun réglage n'y change rien"),
            ('three-ways-to-close-the-gap', "Trois façons de combler l'écart"),
            ('compliance-features-already-in-the-platform', 'Fonctions de conformité déjà présentes dans la plateforme'),
        ],
        'evidence': [
            ('layer-1-the-runtime-judge', "Niveau 1 — L'évaluateur à l'exécution"),
            ('layer-2-turn-level-evaluation-against-a-rubric', 'Niveau 2 — Évaluation par tour selon une grille'),
            ('layer-3-session-level-pedagogical-evaluation', 'Niveau 3 — Évaluation pédagogique au niveau de la séance'),
            ('the-quality-gate-to-apply-before-a-cohort', 'Le contrôle qualité à appliquer avant une cohorte'),
        ],
        'executive-summary': [
            ('the-five-things-a-country-adapts', "Les cinq choses qu'un pays adapte"),
            ('the-one-decision-that-changes-everything-else', 'La décision qui conditionne toutes les autres'),
            ('cost-shape', 'Profil de coûts'),
            ('time-to-a-first-cohort', "Délai jusqu'à une première cohorte"),
        ],
        'five-layers': [
            ('layer-1-language-and-register', 'Couche 1 — Langue et registre'),
            ('layer-2-curriculum', 'Couche 2 — Programme'),
            ('layer-3-local-context', 'Couche 3 — Contexte local'),
            ('layer-4-national-structures', 'Couche 4 — Structures nationales'),
            ('layer-5-infrastructure-and-data-residency', 'Couche 5 — Infrastructure et résidence des données'),
        ],
        'governance': [
            ('roles-that-need-a-name-against-them', 'Les rôles auxquels il faut associer un nom'),
            ('what-the-country-supplies', 'Ce que le pays fournit'),
            ('what-the-platform-supplies', 'Ce que la plateforme fournit'),
        ],
        'hosting': [
            ('choosing-a-path', 'Choisir un parcours'),
            ('path-a-one-server', 'Parcours A — un serveur'),
            ('path-b-your-own-aws-account', 'Parcours B — votre propre compte AWS'),
            ('path-c-pip-install-no-docker', 'Parcours C — installation par pip, sans Docker'),
            ('the-two-offline-shapes', 'Les deux formats hors ligne'),
            ('when-something-is-wrong', 'Quand quelque chose ne va pas'),
            ('backup-and-restore', 'Sauvegarde et restauration'),
            ('logs', 'Journaux'),
        ],
        'language-locale': [
            ('locale-codes', 'Codes de localité'),
            ('the-five-places-a-locale-is-registered', 'Les cinq endroits où une localité est enregistrée'),
            ('which-language-wins-per-request', "Quelle langue l'emporte, à chaque requête"),
            ('register-decisions-to-settle-with-a-native-speaking-educator', 'Décisions de registre à trancher avec un enseignant locuteur natif'),
        ],
        'teacher-training': [
            ('what-a-teacher-has-to-be-able-to-do-and-when', "Ce qu'un enseignant doit savoir faire, et quand"),
            ('a-three-tier-training-model', 'Un modèle de formation à trois niveaux'),
            ('who-trains-whom', 'Qui forme qui'),
            ('three-lines-of-support', 'Trois niveaux de soutien'),
            ('what-to-measure', "Ce qu'il faut mesurer"),
            ('failure-modes-specific-to-training', 'Modes de défaillance propres à la formation'),
        ],
        'what-is-adopted': [
            ('for-the-student', "Pour l'élève"),
            ('for-the-teacher', "Pour l'enseignant"),
            ('for-the-ministry', 'Pour le ministère'),
            ('the-content-pipeline', 'La chaîne de production du contenu'),
            ('the-quality-layer', 'La couche qualité'),
        ],
    },
    'pt_mz': {
        'adoption-models': [
            ('the-offline-options-in-more-detail', 'As opções offline em mais detalhe'),
            ('choosing-between-them', 'Escolher entre eles'),
        ],
        'cost-sharing': [
            ('the-cost-lines-behave-differently-so-share-them-differently', 'As rubricas de custo comportam-se de forma diferente, por isso partilhe-as de forma diferente'),
            ('four-funding-models', 'Quatro modelos de financiamento'),
            ('making-the-recurring-line-small', 'Tornar pequena a rubrica recorrente'),
            ('a-cost-per-student-figure-you-can-defend', 'Um custo por aluno que consegue defender'),
            ('sustainability-is-not-only-financial', 'A sustentabilidade não é apenas financeira'),
            ('what-to-write-into-the-funding-agreement', 'O que escrever no acordo de financiamento'),
        ],
        'costs': [
            ('fixed-infrastructure-a-country-owned-cloud-instance', 'Infra-estrutura fixa — uma instância de nuvem pertencente ao país'),
            ('variable-cost-the-model-and-it-dominates', 'Custo variável — o modelo, e é ele que domina'),
            ('levers-in-the-order-worth-pulling-them', 'Alavancas, pela ordem por que vale a pena accioná-las'),
            ('modelling-it-for-your-country', 'Modelar isto para o seu país'),
        ],
        'curriculum-pipeline': [
            ('two-routes-in', 'Duas vias de entrada'),
            ('the-generation-pipeline', 'O pipeline de geração'),
            ('practical-notes', 'Notas práticas'),
        ],
        'data-sovereignty': [
            ('what-stays-where-you-put-it', 'O que fica onde o colocar'),
            ('what-leaves-and-why-no-setting-changes-it', 'O que sai, e porque nenhuma configuração o altera'),
            ('three-ways-to-close-the-gap', 'Três formas de fechar essa lacuna'),
            ('compliance-features-already-in-the-platform', 'Funcionalidades de conformidade já existentes na plataforma'),
        ],
        'evidence': [
            ('layer-1-the-runtime-judge', 'Nível 1 — O avaliador em execução'),
            ('layer-2-turn-level-evaluation-against-a-rubric', 'Nível 2 — Avaliação por turno segundo uma rubrica'),
            ('layer-3-session-level-pedagogical-evaluation', 'Nível 3 — Avaliação pedagógica ao nível da sessão'),
            ('the-quality-gate-to-apply-before-a-cohort', 'O critério de qualidade a aplicar antes de uma turma'),
        ],
        'executive-summary': [
            ('the-five-things-a-country-adapts', 'As cinco coisas que um país adapta'),
            ('the-one-decision-that-changes-everything-else', 'A decisão que altera todas as outras'),
            ('cost-shape', 'Perfil de custos'),
            ('time-to-a-first-cohort', 'Tempo até uma primeira turma'),
        ],
        'five-layers': [
            ('layer-1-language-and-register', 'Camada 1 — Língua e registo'),
            ('layer-2-curriculum', 'Camada 2 — Currículo'),
            ('layer-3-local-context', 'Camada 3 — Contexto local'),
            ('layer-4-national-structures', 'Camada 4 — Estruturas nacionais'),
            ('layer-5-infrastructure-and-data-residency', 'Camada 5 — Infra-estrutura e residência dos dados'),
        ],
        'governance': [
            ('roles-that-need-a-name-against-them', 'Papéis que precisam de um nome associado'),
            ('what-the-country-supplies', 'O que o país fornece'),
            ('what-the-platform-supplies', 'O que a plataforma fornece'),
        ],
        'hosting': [
            ('choosing-a-path', 'Escolher um caminho'),
            ('path-a-one-server', 'Caminho A — um servidor'),
            ('path-b-your-own-aws-account', 'Caminho B — a sua própria conta AWS'),
            ('path-c-pip-install-no-docker', 'Caminho C — instalação com pip, sem Docker'),
            ('the-two-offline-shapes', 'Os dois formatos offline'),
            ('when-something-is-wrong', 'Quando algo corre mal'),
            ('backup-and-restore', 'Cópias de segurança e restauro'),
            ('logs', 'Registos'),
        ],
        'language-locale': [
            ('locale-codes', 'Códigos de localidade'),
            ('the-five-places-a-locale-is-registered', 'Os cinco sítios onde uma localidade é registada'),
            ('which-language-wins-per-request', 'Que língua prevalece, em cada pedido'),
            ('register-decisions-to-settle-with-a-native-speaking-educator', 'Decisões de registo a fechar com um educador falante nativo'),
        ],
        'teacher-training': [
            ('what-a-teacher-has-to-be-able-to-do-and-when', 'O que um professor tem de saber fazer, e quando'),
            ('a-three-tier-training-model', 'Um modelo de formação em três níveis'),
            ('who-trains-whom', 'Quem forma quem'),
            ('three-lines-of-support', 'Três linhas de apoio'),
            ('what-to-measure', 'O que medir'),
            ('failure-modes-specific-to-training', 'Modos de falha próprios da formação'),
        ],
        'what-is-adopted': [
            ('for-the-student', 'Para o aluno'),
            ('for-the-teacher', 'Para o professor'),
            ('for-the-ministry', 'Para o ministério'),
            ('the-content-pipeline', 'O pipeline de conteúdos'),
            ('the-quality-layer', 'A camada de qualidade'),
        ],
    },
}
