# Generated by Django 6.0.2 on 2026-02-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_membership_role_alter_staffinvitation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='accent_color',
            field=models.CharField(default='#FFE66D', max_length=7),
        ),
        migrations.AddField(
            model_name='institution',
            name='custom_css',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institution_logos/'),
        ),
        migrations.AddField(
            model_name='institution',
            name='primary_color',
            field=models.CharField(default='#E8590C', max_length=7),
        ),
        migrations.AddField(
            model_name='institution',
            name='secondary_color',
            field=models.CharField(default='#4ECDC4', max_length=7),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('staff', 'Staff (Teacher/Admin)'), ('student', 'Student')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffinvitation',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('staff', 'Staff (Teacher/Admin)'), ('student', 'Student')], default='staff', max_length=20),
        ),
    ]
