# Generated by Django 6.0.2 on 2026-02-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_platformconfig_remove_institution_custom_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff (Teacher/Admin)'), ('student', 'Student')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffinvitation',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='staffinvitation',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff (Teacher/Admin)'), ('student', 'Student')], default='staff', max_length=20),
        ),
    ]
