# Generated by Django 6.0.2 on 2026-02-25 20:38

from django.db import migrations


def copy_branding_forward(apps, schema_editor):
    """Copy branding from the first Institution to PlatformConfig.

    This uses the OLD schema (before branding fields were removed from
    Institution) via a raw SQL approach, since the schema migration
    0008 already removed them from the model.  We use RunSQL instead.
    """
    pass  # handled by RunSQL below


def seed_schools_from_config(apps, schema_editor):
    """Create Institution records from PlatformConfig.schools JSON entries."""
    PlatformConfig = apps.get_model('accounts', 'PlatformConfig')
    Institution = apps.get_model('accounts', 'Institution')

    try:
        config = PlatformConfig.objects.get(pk=1)
    except PlatformConfig.DoesNotExist:
        return

    if not config.schools:
        return

    for entry in config.schools:
        code = entry.get('code', '').strip()
        name = entry.get('name', '').strip()
        if code and name:
            slug = code.replace(' ', '-').replace('_', '-').lower()
            if not Institution.objects.filter(slug=slug).exists():
                Institution.objects.create(
                    name=name,
                    slug=slug,
                    timezone='Indian/Mahe',
                    is_active=True,
                )


def migrate_platform_prompt_packs(apps, schema_editor):
    """Move institution-bound PromptPacks to platform-wide (institution=NULL)."""
    PromptPack = apps.get_model('llm', 'PromptPack')
    # For any active prompt packs, set institution to NULL (platform-wide)
    PromptPack.objects.filter(is_active=True).update(institution=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_move_branding_to_platformconfig'),
        ('llm', '0003_make_promptpack_institution_nullable'),
    ]

    operations = [
        migrations.RunPython(seed_schools_from_config, migrations.RunPython.noop),
        migrations.RunPython(migrate_platform_prompt_packs, migrations.RunPython.noop),
    ]
