# Generated by Django 6.0.2 on 2026-04-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_tutor_personality'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='threshold_ae_max',
            field=models.IntegerField(default=80, help_text='Approaching Expectation (AE): BE threshold to this value (exclusive). Default: 80%'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='threshold_be_max',
            field=models.IntegerField(default=50, help_text='Below Expectation (BE): 0% to this value (exclusive). Default: 50%'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='threshold_ee_time_minutes',
            field=models.IntegerField(default=5, help_text='Exceeding Expectation (EE): 100% objectives + exit ticket completed under this many minutes. Default: 5'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='threshold_me_min',
            field=models.IntegerField(default=80, help_text='Meeting Expectation (ME): this value to 100% (exclusive). Default: 80%'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='threshold_move_on',
            field=models.IntegerField(default=70, help_text='Recommend teacher to move on when ALL students achieve at least this % of objectives. Default: 70%'),
        ),
    ]
