# Generated by Django 6.0.2 on 2026-04-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_teachers_can_edit_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_tutor_suspended',
            field=models.BooleanField(default=False, help_text='Locked out of AI tutor due to safety violations. Teacher must review and re-approve.'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tutor_suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tutor_suspended_reason',
            field=models.TextField(blank=True, help_text='Reason for suspension (auto-filled from safety flags)'),
        ),
    ]
