# Generated by Django 6.0.2 on 2026-04-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_student_tutor_suspension'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, default='', help_text='Unique student ID from school management system (e.g., STU-2024-001)', max_length=50),
        ),
    ]
