# Generated by Django 6.0.2 on 2026-04-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_student_groups_and_session_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='skills_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills_snapshot_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
