# Generated by Django 6.0.2 on 2026-04-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_student_skills_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(default='AI Tutor — Terms', max_length=200)),
                ('summary', models.CharField(blank=True, help_text='One-line summary shown beside the checkbox at sign-up.', max_length=300)),
                ('body', models.TextField(help_text='Full terms text (Markdown / plain HTML).')),
                ('is_active', models.BooleanField(default=False)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Platform terms',
                'verbose_name_plural': 'Platform terms',
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='terms_accepted_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
