# Generated by Django 6.0.2 on 2026-05-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_emailverificationtoken_useremailstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='teachers_can_regenerate_courses',
            field=models.BooleanField(default=False, help_text='If False, teachers cannot trigger course-level regenerate (rebuilds every lesson + exit ticket in the course). Per-lesson regenerate is gated separately by teachers_can_edit_content.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='teachers_can_upload_curriculum',
            field=models.BooleanField(default=False, help_text='If False, teachers cannot upload new curriculum (PDF/DOCX → course generation). Super admin only by default — uploads are destructive and rebuild the whole course.'),
        ),
        migrations.AlterField(
            model_name='platformconfig',
            name='teachers_can_edit_content',
            field=models.BooleanField(default=False, help_text='If False, teachers can only view content and reports — they cannot edit, publish, or delete lesson content. Super admins always have full access.'),
        ),
    ]
