# Generated by Django 6.0.2 on 2026-05-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_pilot_permission_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='password_reset_required',
            field=models.BooleanField(default=False),
        ),
    ]
