# Generated by Django 6.0.2 on 2026-05-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_membership_password_reset_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='asked_questions',
            field=models.JSONField(blank=True, default=dict, help_text='Structured map keyed by "{source}:{id}" (e.g. "exit_ticket_question:7"); values {last_asked_at: iso8601}. Drives cross-session repeat avoidance.'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_summary',
            field=models.TextField(blank=True, default='', help_text="Qualitative recall of the student's strengths / struggles / examples shown, written by StudentProfiler at end-of-session."),
        ),
    ]
