# Generated by Django 6.0.2 on 2026-06-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_widen_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformterms',
            name='locale',
            field=models.CharField(db_index=True, default='en-us', help_text="UI locale these terms are written in (e.g. 'en-us', 'pt-mz').", max_length=10),
        ),
        migrations.AlterField(
            model_name='platformterms',
            name='version',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='platformterms',
            unique_together={('version', 'locale')},
        ),
    ]
