# Generated by Django 6.0.2 on 2026-08-06 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_add_student_tutor_mode'),
        ('llm', '0033_add_vertex_model_garden_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='offline_model',
            field=models.ForeignKey(blank=True, help_text='Which local model the offline tutor uses. Blank = let the platform choose. Only meaningful when more than one local model is installed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='llm.modelconfig'),
        ),
    ]
