# Generated by Django 6.0.2 on 2026-08-09 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_add_student_offline_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(blank=True, default='', help_text='Whatever a teacher will recognise: "Lab laptop 3".', max_length=120)),
                ('enrolment_code', models.CharField(db_index=True, help_text='Short code typed into the device once. Single use.', max_length=12, unique=True)),
                ('token_hash', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Awaiting enrolment'), ('active', 'Active'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last successful sync. How a teacher spots a device that has stopped reporting.', null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.institution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
