# Generated by Django 6.0.2 on 2026-03-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StepMedia',
        ),
    ]
