# Generated by Django 6.0.2 on 2026-02-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0003_exit_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitticketquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation of the correct answer'),
        ),
    ]
