# Generated by Django 6.0.2 on 2026-02-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0005_skill_studentskillmastery_skillpracticelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitticketquestion',
            name='concept_tag',
            field=models.CharField(blank=True, help_text='The concept/objective this question assesses', max_length=200),
        ),
    ]
