# Generated by Django 6.0.2 on 2026-04-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0008_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitticketquestion',
            name='answer_data',
            field=models.JSONField(blank=True, help_text='Type-specific answer data:\n        fill_in_blank: {"text_template": "The ___ is...", "blanks": ["GNP"], "accept_alternatives": [["gross national product"]]}\n        matching: {"pairs": [{"left": "A", "right": "1"}], "distractor_rights": ["X"]}\n        short_answer: {"model_answer": "...", "keywords": ["k1", "k2"], "min_keywords": 2}\n        data_interpretation: {"data_description": "...", "model_answer": "...", "keywords": [...]}\n        ', null=True),
        ),
        migrations.AddField(
            model_name='exitticketquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('fill_in_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('short_answer', 'Short Answer'), ('data_interpretation', 'Data Interpretation')], default='mcq', help_text='Question format type', max_length=25),
        ),
        migrations.AlterField(
            model_name='exitticketquestion',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', help_text='The correct option for MCQ (A, B, C, or D)', max_length=1),
        ),
        migrations.AlterField(
            model_name='exitticketquestion',
            name='option_a',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='exitticketquestion',
            name='option_b',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='exitticketquestion',
            name='option_c',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='exitticketquestion',
            name='option_d',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
