# Generated by Django 6.0.2 on 2026-04-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0009_exit_ticket_question_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='enabling_objective_text',
            field=models.CharField(blank=True, default='', help_text='Source enabling objective text from syllabus (if this skill was derived from an EO)', max_length=500),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_enabling_objective',
            field=models.BooleanField(default=False, help_text='True if this skill was auto-created from a curriculum enabling objective'),
        ),
    ]
