# Generated by Django 6.0.2 on 2026-04-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0010_skill_enabling_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='source_code',
            field=models.CharField(blank=True, default='', help_text='Original curriculum code if any (e.g. K408, S401, S510)', max_length=20),
        ),
    ]
