# Generated by Django 6.0.2 on 2026-04-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0011_skill_source_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='objective_type',
            field=models.CharField(blank=True, choices=[('terminal', 'Terminal Objective'), ('enabling', 'Enabling Objective'), ('', 'Not specified')], default='', help_text='Whether this is a terminal (assessment) or enabling (teaching step) objective', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='enabling_objective_text',
            field=models.CharField(blank=True, default='', help_text='Source objective text from syllabus', max_length=500),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_enabling_objective',
            field=models.BooleanField(default=False, help_text='True if this skill was auto-created from a curriculum objective'),
        ),
    ]
