# Generated by Django 6.0.2 on 2026-04-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0012_skill_objective_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='completed_lesson_at',
            field=models.DateTimeField(blank=True, help_text='When the student completed the lesson content', null=True),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='started_lesson_at',
            field=models.DateTimeField(blank=True, help_text='When the student started the lesson content', null=True),
        ),
    ]
