# Generated by Django 6.0.2 on 2026-04-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0019_group_lessons_v2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlessonprogress',
            name='correct_streak',
        ),
        migrations.RemoveField(
            model_name='studentlessonprogress',
            name='total_attempts',
        ),
        migrations.RemoveField(
            model_name='studentlessonprogress',
            name='total_correct',
        ),
    ]
