# Generated by Django 6.0.2 on 2026-04-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0022_summative_assessments'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitticketattempt',
            name='purpose',
            field=models.CharField(choices=[('practice', 'Practice / lesson exit ticket'), ('baseline', 'Baseline (pre-course summative)'), ('final', 'Final (post-course summative)'), ('retake', 'Retake')], default='practice', help_text="What this attempt counts as. Baseline + Final on a summative drive the dashboard's longitudinal competency view.", max_length=15),
        ),
    ]
