# Generated by Django 6.0.2 on 2026-05-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0026_exit_ticket_question_template_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitticketquestion',
            name='enabling_objective',
            field=models.CharField(blank=True, default='', help_text="Specific enabling objective (sub-objective) this question tests — must match one of the parent lesson's enabling objectives. Promoted to a first-class field 2026-05-01 so remediation can target the failing sub-skill instead of the whole learning objective.", max_length=500),
        ),
        migrations.AlterField(
            model_name='exitticketquestion',
            name='concept_tag',
            field=models.CharField(blank=True, help_text="Broader learning-objective tag (or short concept slug) the question is grouped under. Often the lesson's main learning objective text. Shown in the dashboard as the broad pill.", max_length=200),
        ),
    ]
