# Generated by Django 6.0.2 on 2026-05-12 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0028_sessionturn_judge_outputs'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('llm_call', 'LLM Call'), ('tool_call', 'Tool Call'), ('judge', 'Judge'), ('regen', 'Regen'), ('audit', 'Audit'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(help_text="Span name. For LLM calls: 'generate'. For judges: 'arithmetic', 'safety', etc.", max_length=100)),
                ('model', models.CharField(blank=True, help_text="Model identifier (e.g. 'claude-opus-4-7'). Empty for non-LLM spans.", max_length=80)),
                ('purpose', models.CharField(blank=True, help_text='ModelConfig.purpose for LLM spans (tutoring, judge, regen, etc.).', max_length=40)),
                ('started_at', models.DateTimeField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('tokens_in', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_out', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Span-specific structured data (e.g. judge verdict summary, tool args, regen reason).')),
                ('error', models.TextField(blank=True, help_text="Error class + message if the span's operation raised. Empty on success.")),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='tutoring.sessionturn')),
            ],
            options={
                'verbose_name': 'Turn Span',
                'ordering': ['started_at'],
                'indexes': [models.Index(fields=['turn', 'started_at'], name='tutoring_tu_turn_id_4b9f49_idx'), models.Index(fields=['kind'], name='tutoring_tu_kind_5e062a_idx')],
            },
        ),
    ]
