# Generated by Django 6.0.2 on 2026-05-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0032_exitticketquestion_content_quality_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='current_question_id',
            field=models.IntegerField(blank=True, help_text='ExitTicketQuestion or LessonStep question id the simple tutor has currently posed. None = no active question.', null=True),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='engine',
            field=models.CharField(choices=[('v1', 'conversational_tutor'), ('simple', 'simple_tutor')], db_index=True, default='v1', help_text='Which runtime engine handles this session. Locked at creation; do not change mid-session.', max_length=16),
        ),
    ]
