# Generated by Django 6.0.2 on 2026-05-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0033_add_engine_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='current_question_source',
            field=models.CharField(blank=True, choices=[('lesson_step', 'LessonStep'), ('exit_ticket', 'ExitTicketQuestion')], help_text='Table current_question_id points to. None when current_question_id is None.', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tutorsession',
            name='current_question_id',
            field=models.IntegerField(blank=True, help_text='LessonStep or ExitTicketQuestion id the simple tutor has anchored to. Disambiguated by current_question_source.', null=True),
        ),
    ]
