# Generated by Django 6.0.2 on 2026-08-09 03:35

from django.conf import settings
from django.db import migrations, models


def backfill_client_uuid(apps, schema_editor):
    """Lift client_uuid out of metadata into the new column.

    The mobile sync endpoint has been writing it into
    ``SessionTurn.metadata['client_uuid']`` and deduping on that. If the column
    started empty, a device re-pushing an already-synced turn would find no
    match on the column and insert a duplicate — the exact bug the constraint
    is meant to prevent, introduced by the fix for it.

    Duplicates already in the data would break the unique constraint, so the
    first occurrence wins and later ones are left NULL rather than failing the
    migration on historical rows nobody can now reconcile.
    """
    SessionTurn = apps.get_model('tutoring', 'SessionTurn')
    seen = set()
    updates = []
    qs = SessionTurn.objects.exclude(metadata={}).only('id', 'metadata').iterator()
    for turn in qs:
        meta = turn.metadata if isinstance(turn.metadata, dict) else {}
        cu = (meta or {}).get('client_uuid')
        if not cu or cu in seen:
            continue
        seen.add(cu)
        turn.client_uuid = cu
        updates.append(turn)
        if len(updates) >= 500:
            SessionTurn.objects.bulk_update(updates, ['client_uuid'])
            updates = []
    if updates:
        SessionTurn.objects.bulk_update(updates, ['client_uuid'])


def unbackfill(apps, schema_editor):
    """No-op: the column is being dropped anyway."""


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0032_add_content_pack_version'),
        ('tutoring', '0035_in_flight_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exitticketattempt',
            name='client_uuid',
            field=models.CharField(blank=True, db_index=True, help_text='Client-generated id for offline sync dedup.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='sessionturn',
            name='client_uuid',
            field=models.CharField(blank=True, db_index=True, help_text='Client-generated id for offline sync dedup.', max_length=64, null=True),
        ),
        migrations.RunPython(backfill_client_uuid, unbackfill),
        migrations.AddConstraint(
            model_name='exitticketattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('client_uuid',), name='uniq_attempt_client_uuid'),
        ),
        migrations.AddConstraint(
            model_name='sessionturn',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('client_uuid',), name='uniq_sessionturn_client_uuid'),
        ),
    ]
