"""The offline-eval viewer's manual grading must not drift from the dashboard.

`offline_eval/build_viewer.py` generates a standalone page that lets a human
grade local transcripts against the same eight dimensions the dashboard uses at
/dashboard/benchmark/sessions/. "The same" is the whole point — a comparison
between a human verdict and the LLM judge's is only meaningful if the human was
asked the dashboard's questions, scored by the dashboard's rule.

Nothing enforces that by construction: the page is a static file with its own
copy of the pass rule in JavaScript, generated by a script that could just as
easily bake a stale taxonomy. So three things are pinned here:

  * the baked dimensions are `pedagogy.DIMENSIONS`, field for field, including
    the n/a option and the desideratum that decides a pass;
  * the JavaScript pass rule agrees with `pedagogy.session_passes` on every
    combination of values, not just the obvious ones — the all-or-nothing rule
    has three outcomes per dimension (pass / fail / excluded) and it is the
    excluded case that silently inverts a verdict when it is got wrong;
  * every run directory on disk is actually on the page, so a new eval cycle
    cannot be graded-around by being invisible.
"""
import json
import random
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from ai_tutor.apps.benchmark import pedagogy as P  # noqa: E402

sys.path.insert(0, str(ROOT / 'offline_eval'))

import build_viewer as BV  # noqa: E402


# ── The taxonomy the page bakes in ──────────────────────────────────────

def test_baked_dimensions_match_pedagogy_exactly():
    """The page's questions are the dashboard's questions.

    Fails if build_viewer grows its own copy of a dimension's wording, drops
    one, reorders them, or lets a desideratum drift.
    """
    baked = BV.dimensions_payload()

    assert [d['key'] for d in baked] == list(P.DIMENSION_KEYS)

    for dim, got in zip(P.DIMENSIONS, baked):
        assert got['label'] == dim.label
        assert got['definition'] == dim.definition
        assert got['guidance'] == dim.session_guidance
        assert got['desideratum'] == dim.desideratum
        # Options carry the n/a choice exactly where pedagogy allows it, in the
        # paper's order — the order is meaningful and the UI renders it as-is.
        assert got['values'] == [list(v) for v in P.choices_for(dim.key)]


def test_baked_dimensions_offer_na_only_where_allowed():
    for dim, got in zip(P.DIMENSIONS, BV.dimensions_payload()):
        has_na = any(v[0] == P.NOT_APPLICABLE for v in got['values'])
        assert has_na is dim.allows_na


# ── The pass rule, in two languages ─────────────────────────────────────

def _value_pool(dim):
    """Everything a dimension can hold in the UI, including 'unanswered'."""
    pool = [v for v, _label in dim.values]
    if dim.allows_na:
        pool.append(P.NOT_APPLICABLE)
    pool.append('')  # not yet answered — excluded, not a failure
    return pool


def _parity_cases():
    """Edge cases that matter, then a deterministic random sweep."""
    keys = list(P.DIMENSION_KEYS)
    desired = {d.key: d.desideratum for d in P.DIMENSIONS}

    cases = [
        {k: desired[k] for k in keys},                       # all good -> pass
        {k: '' for k in keys},                               # nothing answered
        {k: P.NOT_APPLICABLE for k in keys},                 # nothing scorable
        # One dimension short of the desideratum fails the whole session.
        *[{**{k: desired[k] for k in keys}, off: P.TO_SOME_EXTENT}
          for off in ('mistake_identification', 'coherence', 'human_likeness')],
        # revealing_answer is the inverted one: its desideratum is "No", so
        # revealing the right answer is still a failure.
        {**{k: desired[k] for k in keys}, 'revealing_answer': P.YES_CORRECT},
        # tutor_tone is stricter than a binary judge: neutral does not pass.
        {**{k: desired[k] for k in keys}, 'tutor_tone': P.NEUTRAL},
        # A single scorable dimension at its desideratum, everything else n/a,
        # passes — n/a is excluded from scoring, not counted against.
        {**{k: P.NOT_APPLICABLE for k in keys},
         'coherence': desired['coherence']},
        # ...but the same shape with that one dimension failing does not.
        {**{k: P.NOT_APPLICABLE for k in keys}, 'coherence': P.NO},
    ]

    rng = random.Random(20260817)
    pools = {d.key: _value_pool(d) for d in P.DIMENSIONS}
    for _ in range(2000):
        cases.append({k: rng.choice(pools[k]) for k in keys})
    return cases


def _run_js(dims, cases, tmp_path):
    """Evaluate the shipped pass rule under node, once, for every case.

    Written to a file rather than passed via `node -e`: two thousand cases
    overflow the argv limit.
    """
    driver = tmp_path / 'parity.js'
    driver.write_text(
        f'const DIMS = {json.dumps(dims)};\n'
        f'{BV.PASS_RULE_JS}\n'
        f'const CASES = {json.dumps(cases)};\n'
        'console.log(JSON.stringify(CASES.map(c => sessionPasses(c))));\n'
    )
    proc = subprocess.run(
        ['node', str(driver)], capture_output=True, text=True, timeout=60,
    )
    assert proc.returncode == 0, f'node failed:\n{proc.stderr}'
    return json.loads(proc.stdout)


def test_js_pass_rule_agrees_with_python_on_every_case(tmp_path):
    """The verdict a grader sees must be the verdict Python would compute.

    Two implementations of one rule is a drift risk we accept (the page has no
    backend), so it is pinned rather than trusted.
    """
    cases = _parity_cases()
    got = _run_js(BV.dimensions_payload(), cases, tmp_path)
    expected = [P.session_passes(c) for c in cases]

    mismatches = [
        (c, e, g) for c, e, g in zip(cases, expected, got) if e != g
    ]
    assert not mismatches, (
        f'{len(mismatches)} of {len(cases)} cases disagree; first: '
        f'{mismatches[0]}'
    )


def test_js_pass_rule_ships_in_the_generated_page(tmp_path):
    """A rule that is tested but not shipped tests nothing."""
    out = tmp_path / 'index.html'
    BV.build(src=_fixture(tmp_path), out=str(out), flat_runs=[])
    assert BV.PASS_RULE_JS in out.read_text()


# ── The summary statistics on the comparison tab ────────────────────────

def _run_stats_js(body, tmp_path):
    """Run a snippet against the page's shipped stats helpers."""
    driver = tmp_path / 'stats.js'
    driver.write_text(
        f'const DIMS = {json.dumps(BV.dimensions_payload())};\n'
        f'{BV.PASS_RULE_JS}\n{BV.STATS_JS}\n{body}\n'
    )
    proc = subprocess.run(
        ['node', str(driver)], capture_output=True, text=True, timeout=60,
    )
    assert proc.returncode == 0, f'node failed:\n{proc.stderr}'
    return json.loads(proc.stdout)


def test_session_score_counts_only_applicable_dimensions(tmp_path):
    """The per-session percentage is over what was actually scorable.

    Dividing by eight instead would punish a session for dimensions that never
    arose, which is the same mistake as counting n/a as a failure.
    """
    desired = {d.key: d.desideratum for d in P.DIMENSIONS}
    cases = [
        {k: desired[k] for k in P.DIMENSION_KEYS},
        # Four at desideratum, four not -> 50% of eight applicable.
        {**{k: desired[k] for k in P.DIMENSION_KEYS},
         **{k: P.TO_SOME_EXTENT for k in list(P.DIMENSION_KEYS)[:4]}},
        # One scorable dimension, the rest never arose -> 100% of one.
        {**{k: P.NOT_APPLICABLE for k in P.DIMENSION_KEYS},
         'coherence': desired['coherence']},
        # Nothing scorable at all.
        {k: P.NOT_APPLICABLE for k in P.DIMENSION_KEYS},
        {k: '' for k in P.DIMENSION_KEYS},
    ]
    got = _run_stats_js(
        f'const C = {json.dumps(cases)};\n'
        'console.log(JSON.stringify(C.map(sessionScore)));', tmp_path)

    assert [g['pct'] for g in got] == [100.0, 50.0, 100.0, None, None]
    assert [g['applicable'] for g in got] == [8, 8, 1, 0, 0]
    # 'to some extent' is scorable-and-failing, not excluded — the mistake that
    # would make the first two cases both read 100%.
    assert got[1]['at'] == 4


def test_persona_balance_lists_personas_with_nothing_graded(tmp_path):
    """A persona you have not touched must appear with a zero bar.

    Dropping it is the one failure that defeats the chart's whole purpose: the
    persona you most need to grade next is the one with no rows to count.
    """
    personas = ['average', 'capable', 'error_prone', 'non_responder',
                'probe_resistant', 'struggler']
    rows = ([{'p': 'average'}] * 5 + [{'p': 'capable'}] * 2
            + [{'p': 'struggler'}] * 5)
    got = _run_stats_js(
        f'console.log(JSON.stringify(personaBalance({json.dumps(rows)}, '
        f'{json.dumps(personas)})));', tmp_path)

    assert [g['persona'] for g in got] == personas
    assert [g['n'] for g in got] == [5, 2, 0, 0, 0, 5]
    # Deficit is measured against the most-graded persona, so "all bars level"
    # is the same statement as "every deficit is zero".
    assert [g['deficit'] for g in got] == [0, 3, 5, 5, 5, 0]
    assert all(g['target'] == 5 for g in got)


def test_persona_balance_of_an_empty_set_is_all_zeroes(tmp_path):
    personas = ['average', 'capable']
    got = _run_stats_js(
        f'console.log(JSON.stringify(personaBalance([], '
        f'{json.dumps(personas)})));', tmp_path)
    assert [g['n'] for g in got] == [0, 0]
    assert [g['deficit'] for g in got] == [0, 0]


def test_non_applicable_rubric_items_read_as_na_not_zero(tmp_path):
    """A rubric item that did not apply carries score 0.0 in the result JSON
    and is excluded from the mean. Printing that 0.00 puts three apparent
    zeroes beside a 97% headline and reads as the tutor having failed something
    it was never asked to do — the same error as counting n/a against a human
    grader, which the pass rule is careful not to make.
    """
    items = [
        {'sc': 0.9, 'ap': True},    # scored
        {'sc': 0.0, 'ap': True},    # a real zero — must still read as 0.00
        {'sc': 0.0, 'ap': False},   # did not apply, stored as 0.0
        {'sc': None, 'ap': True},   # nothing recorded
    ]
    got = _run_stats_js(
        f'console.log(JSON.stringify({json.dumps(items)}.map(rubricDisplay)));',
        tmp_path)

    assert [g['na'] for g in got] == [False, False, True, True]
    assert [g['text'] for g in got] == ['0.90', '0.00', 'n/a', 'n/a']
    # An n/a item draws no bar; a genuine 0.00 also draws none but is not n/a.
    assert [g['width'] for g in got] == [90.0, 0.0, 0.0, 0.0]


def test_pass_rates_are_null_rather_than_zero_for_an_empty_set(tmp_path):
    """0% would assert the tutor failed everything. Nothing was measured."""
    got = _run_stats_js(
        'console.log(JSON.stringify([passRates([]), passRates('
        '[{h:true,j:false},{h:true,j:true},{h:false,j:true},{h:false,j:true}])]));',
        tmp_path)
    assert got[0] == {'n': 0, 'mine': None, 'judge': None}
    assert got[1] == {'n': 4, 'mine': 50.0, 'judge': 75.0}


# ── Coverage of the data itself ─────────────────────────────────────────

def test_runs_list_covers_every_result_location():
    """A new eval cycle must not land on disk and stay off the page.

    This is the failure that made the page show 580 of 860 sessions: seven
    cycle directories existed and were never added to RUNS. Cycle 6 was a
    second, quieter instance of the same bug — its result files sit at the top
    of the results tree rather than in a subdirectory of their own, so a check
    that only walked directories would have declared the page complete while
    sixty sessions stayed invisible. The empty string is how RUNS spells "the
    top level", so it is checked as one more location.
    """
    src = Path(BV.SRC)
    if not src.is_dir():
        pytest.skip(f'no local results at {src}')

    on_disk = {
        d.name for d in src.iterdir()
        if d.is_dir() and any(d.glob('*.json'))
    }
    if any(src.glob('*.json')):
        on_disk.add('')

    listed = {sub for sub, _label in BV.RUNS}
    assert not (on_disk - listed), (
        f'result locations missing from build_viewer.RUNS: '
        f'{sorted(on_disk - listed)}'
    )


def test_declared_flat_runs_exist_on_disk():
    """A result set named in FLAT_RUNS but absent from disk contributes nothing
    and says nothing about it — the page would just be quietly short."""
    for sub, label in BV.FLAT_RUNS:
        path = Path(BV.RESULTS) / sub
        if not path.is_dir():
            pytest.skip(f'{label}: {path} not present in this checkout')
        assert any(path.glob('*.json')), f'{label}: no result JSONs in {path}'


def test_mt100_board_is_on_the_page():
    """The 18-arm, 100-scenario board is the newest result set and the one most
    worth grading. It lives outside the fixcheck cycle tree, in a flat directory
    of one JSON per arm, so the cycle-directory walk alone never reaches it."""
    if not (Path(BV.RESULTS) / 'mt100').is_dir():
        pytest.skip('mt100 results not present in this checkout')

    sessions = BV.collect()
    mt100 = [s for s in sessions if s['run'].endswith('mt100_18arm_board')]

    assert len(mt100) == 1800, f'expected 18 arms x 100 scenarios, got {len(mt100)}'
    assert len({s['m'] for s in mt100}) == 18
    assert len({s['s'] for s in mt100}) == 100
    # The grading UI needs a judge verdict to compare against.
    assert all(s['rp'] is not None for s in mt100)


def test_every_session_on_the_page_has_a_unique_key():
    """Grades are stored against `k`. A collision would silently overwrite one
    session's verdict with another's."""
    src = Path(BV.SRC)
    if not src.is_dir():
        pytest.skip(f'no local results at {src}')

    keys = [s['k'] for s in BV.collect()]
    dupes = {k for k in keys if keys.count(k) > 1}
    assert not dupes, f'duplicate session keys: {sorted(dupes)[:5]}'


# ── The generated page ──────────────────────────────────────────────────

def _fixture(tmp_path):
    """Two sessions in the real result shape: one the judge passed, one not."""
    src = tmp_path / 'results'
    run = src / '_cycle0_baseline'
    run.mkdir(parents=True)

    def session(sid, passed, mean):
        return {
            'scenario_id': sid, 'persona': 'average', 'subject': 'math',
            'lesson_id': 1141, 'sim_reason': 'exit_ticket', 'passed': passed,
            'sim_turns': 12, 'error': None,
            'transcript': [
                {'role': 'tutor', 'phase': 'engage', 'content': 'Hello.'},
                {'role': 'student', 'phase': None, 'content': 'Hi.'},
            ],
            'rubric_result': {
                'mean_score': mean, 'pass_threshold': 0.6, 'passed': passed,
                'items': [{'item': 'Teaches rather than quizzes.',
                           'score': mean, 'applicable': True,
                           'reasoning': 'Explains before asking.'}],
            },
        }

    (run / 'test-model.json').write_text(json.dumps({'results': [
        session('scenario_a', True, 0.82),
        session('scenario_b', False, 0.41),
    ]}))
    return str(src)


def test_generated_page_carries_the_grading_surface(tmp_path):
    out = tmp_path / 'index.html'
    BV.build(src=_fixture(tmp_path), out=str(out), flat_runs=[])
    html = out.read_text()

    # The three new views the grading workflow needs.
    for view in ('grade', 'sxs', 'agreement'):
        assert f'data-v="{view}"' in html, f'no {view} tab on the page'

    # The taxonomy travels with the page rather than being fetched.
    assert 'const DIMS =' in html
    assert 'mistake_identification' in html
    # Every dimension's guidance is present, so a grader reads the same
    # instructions the dashboard shows.
    for dim in P.DIMENSIONS:
        assert dim.session_guidance[:40] in html


def test_generated_page_has_no_network_references(tmp_path):
    """The page's defining property: one file, opens anywhere, calls nothing."""
    out = tmp_path / 'index.html'
    BV.build(src=_fixture(tmp_path), out=str(out), flat_runs=[])
    html = out.read_text()

    for bad in ('src="http', 'href="http', 'fetch(', 'XMLHttpRequest'):
        assert bad not in html, f'page reaches the network via {bad!r}'


def test_model_counts_group_graded_sessions_by_model(tmp_path):
    """The model dropdown's labels carry their own session counts.

    A model with nothing graded is absent by design, and that is the opposite
    of the persona chart's rule one function above. The two lists answer
    different questions: personas are a worklist to level out, so a zero must
    be visible; models are scopes to compare, and an empty scope shows nothing
    but zeroes and dashes if you can select it.
    """
    sessions = ([{'m': 'qwen3-30b'}] * 4 + [{'m': 'deepseek-v3.1'}] * 2
                + [{'m': 'gemini-2.5-flash'}])
    got = _run_stats_js(
        f'console.log(JSON.stringify(modelCounts({json.dumps(sessions)})));',
        tmp_path)

    assert [g['model'] for g in got] == ['deepseek-v3.1', 'gemini-2.5-flash',
                                         'qwen3-30b']
    assert [g['n'] for g in got] == [2, 1, 4]


def test_model_counts_of_an_empty_set_is_empty(tmp_path):
    got = _run_stats_js('console.log(JSON.stringify(modelCounts([])));',
                        tmp_path)
    assert got == []


def test_me_vs_judge_tab_filters_by_model(tmp_path):
    """The comparison tab scopes to one model.

    Without it the pass rates on that tab are a single pooled number across
    every model in the run, which is the one figure that cannot answer "does
    the judge agree with me about THIS model".
    """
    out = tmp_path / 'index.html'
    BV.build(src=_fixture(tmp_path), out=str(out), flat_runs=[])
    html = out.read_text()

    assert 'id="x-model"' in html, 'no model filter on the me-vs-judge tab'
    # The filter has to reach the figures, not just the session list: the
    # summary, the session dropdown and the persona chart all read it.
    for fn in ('drawSxsSummary', 'fillSxsSel', 'personaChart'):
        assert fn in html
    assert "v('x-model')" in html


def test_me_vs_judge_tab_filters_by_subject(tmp_path):
    """The comparison tab scopes to one subject.

    The boards mix maths and geography sessions, and the two are not the same
    measurement: a tutor that holds up on a geography lesson can fall apart on
    arithmetic, so a pooled pass rate hides exactly the gap worth reading. The
    subject has to reach the same three places the model filter does — the
    headline rates, the session list, and the persona chart — or the tab shows
    a figure for one scope beside a list for another.
    """
    out = tmp_path / 'index.html'
    BV.build(src=_fixture(tmp_path), out=str(out), flat_runs=[])
    html = out.read_text()

    assert 'id="x-subject"' in html, 'no subject filter on the me-vs-judge tab'
    assert "v('x-subject')" in html
    # gradedRows is the single gate the KPIs pass through; the subject has to
    # be one of the keys it is handed, not filtered separately downstream.
    assert 'subject:subject' in html
    # The scope helpers behind the session list and the persona chart take it
    # too, so all three read the same set.
    for call in ('gradedSessions(run,\'\',subject)',
                 'gradedSessions(run,model,subject)',
                 'personasIn(run,model,subject)'):
        assert call in html, f'{call} missing — a filter that stops at the KPIs'


# ── The export scope picker ─────────────────────────────────────────────

def _run_export_js(body, tmp_path):
    """Run a snippet against the page's shipped export helpers.

    `exportGroups` and `exportPayload` both call `gradeComplete`, which lives
    in the pass rule, so the driver carries both blocks.
    """
    driver = tmp_path / 'export.js'
    driver.write_text(
        f'const DIMS = {json.dumps(BV.dimensions_payload())};\n'
        f'{BV.PASS_RULE_JS}\n{BV.EXPORT_JS}\n{body}\n'
    )
    proc = subprocess.run(
        ['node', str(driver)], capture_output=True, text=True, timeout=60,
    )
    assert proc.returncode == 0, f'node failed:\n{proc.stderr}'
    return json.loads(proc.stdout)


def _verdict(complete=True):
    """A stored grading — every dimension answered, or one short of it."""
    keys = [d.key for d in P.DIMENSIONS]
    values = {k: P.YES for k in keys}
    if not complete:
        values.pop(keys[-1])
    return {'d': values, 'notes': '', 'peeked': False,
            'ts': '2026-08-25T09:00:00.000Z'}


def _store():
    """Two runs, three arms, with a part-finished grading in one of them."""
    return {
        '46_geo_cloud_3arm|gpt-5.4-mini|s1': _verdict(),
        '46_geo_cloud_3arm|gpt-5.4-mini|s2': _verdict(),
        '46_geo_cloud_3arm|gemini-3.5-flash|s1': _verdict(),
        '46_geo_cloud_3arm|gemini-3.5-flash|s2': _verdict(complete=False),
        '30_mt100_18arm_board|qwen3-30b|s9': _verdict(),
    }


def test_export_groups_are_run_by_model_with_their_counts(tmp_path):
    """The picker's rows. Part-finished gradings are counted separately rather
    than folded into `complete` — the number a grader recognises as "how much
    of this arm have I done" is the completed one."""
    got = _run_export_js(
        f'console.log(JSON.stringify(exportGroups({json.dumps(_store())})));',
        tmp_path)

    assert [(g['run'], g['model'], g['complete'], g['partial']) for g in got] == [
        ('30_mt100_18arm_board', 'qwen3-30b', 1, 0),
        ('46_geo_cloud_3arm', 'gemini-3.5-flash', 1, 1),
        ('46_geo_cloud_3arm', 'gpt-5.4-mini', 2, 0),
    ]


def test_export_groups_keep_scopes_that_left_the_page(tmp_path):
    """Grouping reads the stored key, not this build's session list.

    A grade whose run was renamed or whose results moved is the work most at
    risk — it exists only in this browser. It must stay exportable.
    """
    store = {'99_a_run_that_moved|some-model|s1': _verdict()}
    got = _run_export_js(
        f'console.log(JSON.stringify(exportGroups({json.dumps(store)})));',
        tmp_path)

    assert len(got) == 1
    assert got[0]['run'] == '99_a_run_that_moved'


def test_export_payload_writes_only_the_selected_arms(tmp_path):
    """The whole point: an unselected arm's grades are absent from the file."""
    got = _run_export_js(
        'console.log(JSON.stringify(exportPayload('
        f'{json.dumps(_store())},'
        '["46_geo_cloud_3arm|gpt-5.4-mini"],'
        f'{json.dumps([d.key for d in P.DIMENSIONS])},'
        '"2026-08-25T10:00:00.000Z")));',
        tmp_path)

    assert sorted(got['verdicts']) == ['46_geo_cloud_3arm|gpt-5.4-mini|s1',
                                       '46_geo_cloud_3arm|gpt-5.4-mini|s2']
    assert got['graded'] == 2
    assert got['version'] == 1
    assert got['dimensions'] == [d.key for d in P.DIMENSIONS]


def test_export_payload_carries_part_finished_grades_but_does_not_count_them(
        tmp_path):
    """An export is a backup before it is a dataset, so work in progress inside
    a selected arm travels with it. `graded` still counts only the complete —
    the meaning manual_grades/README.md documents, and the meaning every file
    written before the picker existed already has."""
    got = _run_export_js(
        'console.log(JSON.stringify(exportPayload('
        f'{json.dumps(_store())},'
        '["46_geo_cloud_3arm|gemini-3.5-flash"],'
        f'{json.dumps([d.key for d in P.DIMENSIONS])},'
        '"2026-08-25T10:00:00.000Z")));',
        tmp_path)

    assert len(got['verdicts']) == 2
    assert got['graded'] == 1


def test_selecting_every_arm_reproduces_the_old_whole_store_export(tmp_path):
    """The picker must not become a way to lose a grade.

    With everything ticked the file is byte-for-byte what the one-click export
    wrote before this feature, filename included, so nothing downstream has to
    special-case files written after it.
    """
    store = _store()
    got = _run_export_js(
        f'const S = {json.dumps(store)};\n'
        'const G = exportGroups(S);\n'
        'const P = exportPayload(S, G.map(g => g.id), '
        f'{json.dumps([d.key for d in P.DIMENSIONS])}, "t");\n'
        'console.log(JSON.stringify({v: P.verdicts, g: P.graded, '
        'n: exportName(G, G.map(x => x.id), P.graded)}));',
        tmp_path)

    assert got['v'] == store
    assert got['g'] == 4
    assert got['n'] == 'manual_grades_4.json'


def test_a_narrowed_export_carries_its_scope_in_the_filename(tmp_path):
    """`manual_grades_34.json` from one arm collides with `manual_grades_34.json`
    from any other arm of the same size — the trap manual_grades/README.md
    documents. A subset says which subset it is."""
    store = _store()
    got = _run_export_js(
        f'const S = {json.dumps(store)};\n'
        'const G = exportGroups(S);\n'
        'const name = (ids, n) => exportName(G, ids, n);\n'
        'console.log(JSON.stringify({'
        '  arm: name(["46_geo_cloud_3arm|gpt-5.4-mini"], 2),'
        '  run: name(["46_geo_cloud_3arm|gpt-5.4-mini",'
        '             "46_geo_cloud_3arm|gemini-3.5-flash"], 3),'
        '  none: name([], 0)'
        '}));',
        tmp_path)

    assert got['arm'] == 'manual_grades_46_geo_cloud_3arm_gpt-5.4-mini_2.json'
    assert got['run'] == 'manual_grades_46_geo_cloud_3arm_3.json'
    assert got['none'] == 'manual_grades_0.json'


def test_export_helpers_ship_in_the_generated_page(tmp_path):
    """Logic that is tested but not shipped tests nothing."""
    out = tmp_path / 'index.html'
    BV.build(src=_fixture(tmp_path), out=str(out), flat_runs=[])
    html = out.read_text()

    assert BV.EXPORT_JS in html
    # The picker itself, not just the helpers behind it.
    assert 'id="expw"' in html
    assert 'function doExport()' in html


# ── The grading form's one bulk action ──────────────────────────────────

def _run_grade_js(body, tmp_path):
    """Run a snippet against the page's shipped grading-form helpers."""
    driver = tmp_path / 'grade.js'
    driver.write_text(
        f'const DIMS = {json.dumps(BV.dimensions_payload())};\n'
        f'{BV.PASS_RULE_JS}\n{BV.GRADE_JS}\n{body}\n'
    )
    proc = subprocess.run(
        ['node', str(driver)], capture_output=True, text=True, timeout=60,
    )
    assert proc.returncode == 0, f'node failed:\n{proc.stderr}'
    return json.loads(proc.stdout)


def test_fill_met_writes_each_dimensions_own_desideratum(tmp_path):
    """"Met" is not one value. Most dimensions want `yes`, but the taxonomy has
    dimensions that pass on something else — filling them all with `yes` would
    record a failing grade as a passing one."""
    got = _run_grade_js('console.log(JSON.stringify(fillMet({})));', tmp_path)

    assert got == {d.key: d.desideratum for d in P.DIMENSIONS}
    # The guard this test exists for: at least one dimension does NOT pass on
    # `yes`, so a blanket fill would be wrong.
    assert {d.desideratum for d in P.DIMENSIONS} != {P.YES}


def test_a_filled_form_passes_the_shipped_rule(tmp_path):
    """One click on an untouched session must produce the all-met verdict the
    button claims, under the same rule the page scores with."""
    got = _run_grade_js(
        'console.log(JSON.stringify(sessionPasses(fillMet({}))));', tmp_path)
    assert got is True


def test_fill_met_never_touches_an_answered_dimension(tmp_path):
    """The restriction that makes a one-click "all met" safe to offer.

    Overwriting a judgement with a pass is how a graded set quietly becomes a
    rubber stamp — and it would be invisible afterwards, because the result
    looks exactly like a session someone graded as fine.
    """
    keys = [d.key for d in P.DIMENSIONS]
    answered = {keys[0]: P.NO, keys[3]: P.NOT_APPLICABLE}
    got = _run_grade_js(
        f'console.log(JSON.stringify(fillMet({json.dumps(answered)})));',
        tmp_path)

    assert keys[0] not in got and keys[3] not in got
    assert sorted(got) == sorted(k for k in keys if k not in answered)


def test_fill_met_on_a_finished_grade_writes_nothing(tmp_path):
    """Nothing left to fill — the button has nothing to do and says so."""
    full = {d.key: d.desideratum for d in P.DIMENSIONS}
    got = _run_grade_js(
        f'console.log(JSON.stringify(fillMet({json.dumps(full)})));', tmp_path)
    assert got == {}


def test_grade_helpers_ship_in_the_generated_page(tmp_path):
    out = tmp_path / 'index.html'
    BV.build(src=_fixture(tmp_path), out=str(out), flat_runs=[])
    html = out.read_text()

    assert BV.GRADE_JS in html
    assert 'function fillMetClick()' in html
    assert 'id="g-fill"' in html


# ── Me vs judge, when there is no judge ─────────────────────────────────

def _rows(spec):
    """`h` is my verdict, `j` the judge's — None where no judge ran."""
    return [{'h': h, 'j': j} for h, j in spec]


def test_my_pass_rate_survives_a_run_the_judge_never_scored(tmp_path):
    """The regression this exists for.

    Runs generated with EVAL_SKIP_RUBRIC=1 carry no rubric on any session, so
    the intersection of "graded by me" and "scored by the judge" is empty.
    Computing both rates over that intersection reported an afternoon of
    hand-grading as a dash. Mine needs no judge.
    """
    mine = _rows([(True, None), (True, None), (False, None), (True, None)])
    got = _run_stats_js(
        f'console.log(JSON.stringify(sxsRates({json.dumps(mine)}, [])));',
        tmp_path)

    assert got['graded'] == 4
    assert got['mine'] == 75.0
    assert got['compared'] == 0
    assert got['judge'] is None


def test_the_two_rates_keep_their_own_denominators(tmp_path):
    """A partially-scored run. The headline rate is over everything graded; the
    judge's is over what the judge actually saw."""
    mine = _rows([(True, True), (True, False), (False, None), (False, None)])
    compared = _rows([(True, True), (True, False)])
    got = _run_stats_js(
        f'console.log(JSON.stringify(sxsRates({json.dumps(mine)}, '
        f'{json.dumps(compared)})));',
        tmp_path)

    assert got['graded'] == 4 and got['mine'] == 50.0
    assert got['compared'] == 2 and got['judge'] == 50.0
    # What a leniency claim must be computed over — not the headline 50%.
    assert got['comparedMine'] == 100.0


def test_comparison_uses_the_intersection_not_the_headline(tmp_path):
    """`mine` and `comparedMine` diverging is the whole reason both exist.

    Saying "you are more lenient than the judge" on the strength of a rate over
    sessions the judge never saw is a claim about nothing.
    """
    mine = _rows([(True, True)] + [(False, None)] * 9)
    compared = _rows([(True, True)])
    got = _run_stats_js(
        f'console.log(JSON.stringify(sxsRates({json.dumps(mine)}, '
        f'{json.dumps(compared)})));',
        tmp_path)

    assert got['mine'] == 10.0
    assert got['comparedMine'] == 100.0
    assert got['judge'] == 100.0


def test_nothing_graded_reports_null_not_zero(tmp_path):
    """0% claims a judgement nobody made — the rule the rest of this file holds."""
    got = _run_stats_js('console.log(JSON.stringify(sxsRates([], [])));',
                        tmp_path)
    assert got == {'graded': 0, 'mine': None, 'compared': 0,
                   'comparedMine': None, 'judge': None}


def test_graded_rows_keeps_my_rows_when_the_judge_is_absent(tmp_path):
    """The split has to survive in the page's own row builder, not just in the
    statistic — that is where the rows were being dropped."""
    out = tmp_path / 'index.html'
    BV.build(src=_fixture(tmp_path), out=str(out), flat_runs=[])
    html = out.read_text()

    assert 'out.mine.push(' in html
    # Ordered before the judge-side filter, or it is dropped again.
    assert html.index('out.mine.push(') < html.index('if(j==null){out.noJudge++')
    assert 'sxsRates(S.mine,S.rows)' in html
