"""The offline-eval viewer's manual grading must not drift from the dashboard.

`offline_eval/build_viewer.py` generates a standalone page that lets a human
grade local transcripts against the same eight dimensions the dashboard uses at
/dashboard/benchmark/sessions/. "The same" is the whole point — a comparison
between a human verdict and the LLM judge's is only meaningful if the human was
asked the dashboard's questions, scored by the dashboard's rule.

Nothing enforces that by construction: the page is a static file with its own
copy of the pass rule in JavaScript, generated by a script that could just as
easily bake a stale taxonomy. So three things are pinned here:

  * the baked dimensions are `pedagogy.DIMENSIONS`, field for field, including
    the n/a option and the desideratum that decides a pass;
  * the JavaScript pass rule agrees with `pedagogy.session_passes` on every
    combination of values, not just the obvious ones — the all-or-nothing rule
    has three outcomes per dimension (pass / fail / excluded) and it is the
    excluded case that silently inverts a verdict when it is got wrong;
  * every run directory on disk is actually on the page, so a new eval cycle
    cannot be graded-around by being invisible.
"""
import json
import random
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from ai_tutor.apps.benchmark import pedagogy as P  # noqa: E402

sys.path.insert(0, str(ROOT / 'offline_eval'))

import build_viewer as BV  # noqa: E402


# ── The taxonomy the page bakes in ──────────────────────────────────────

def test_baked_dimensions_match_pedagogy_exactly():
    """The page's questions are the dashboard's questions.

    Fails if build_viewer grows its own copy of a dimension's wording, drops
    one, reorders them, or lets a desideratum drift.
    """
    baked = BV.dimensions_payload()

    assert [d['key'] for d in baked] == list(P.DIMENSION_KEYS)

    for dim, got in zip(P.DIMENSIONS, baked):
        assert got['label'] == dim.label
        assert got['definition'] == dim.definition
        assert got['guidance'] == dim.session_guidance
        assert got['desideratum'] == dim.desideratum
        # Options carry the n/a choice exactly where pedagogy allows it, in the
        # paper's order — the order is meaningful and the UI renders it as-is.
        assert got['values'] == [list(v) for v in P.choices_for(dim.key)]


def test_baked_dimensions_offer_na_only_where_allowed():
    for dim, got in zip(P.DIMENSIONS, BV.dimensions_payload()):
        has_na = any(v[0] == P.NOT_APPLICABLE for v in got['values'])
        assert has_na is dim.allows_na


# ── The pass rule, in two languages ─────────────────────────────────────

def _value_pool(dim):
    """Everything a dimension can hold in the UI, including 'unanswered'."""
    pool = [v for v, _label in dim.values]
    if dim.allows_na:
        pool.append(P.NOT_APPLICABLE)
    pool.append('')  # not yet answered — excluded, not a failure
    return pool


def _parity_cases():
    """Edge cases that matter, then a deterministic random sweep."""
    keys = list(P.DIMENSION_KEYS)
    desired = {d.key: d.desideratum for d in P.DIMENSIONS}

    cases = [
        {k: desired[k] for k in keys},                       # all good -> pass
        {k: '' for k in keys},                               # nothing answered
        {k: P.NOT_APPLICABLE for k in keys},                 # nothing scorable
        # One dimension short of the desideratum fails the whole session.
        *[{**{k: desired[k] for k in keys}, off: P.TO_SOME_EXTENT}
          for off in ('mistake_identification', 'coherence', 'human_likeness')],
        # revealing_answer is the inverted one: its desideratum is "No", so
        # revealing the right answer is still a failure.
        {**{k: desired[k] for k in keys}, 'revealing_answer': P.YES_CORRECT},
        # tutor_tone is stricter than a binary judge: neutral does not pass.
        {**{k: desired[k] for k in keys}, 'tutor_tone': P.NEUTRAL},
        # A single scorable dimension at its desideratum, everything else n/a,
        # passes — n/a is excluded from scoring, not counted against.
        {**{k: P.NOT_APPLICABLE for k in keys},
         'coherence': desired['coherence']},
        # ...but the same shape with that one dimension failing does not.
        {**{k: P.NOT_APPLICABLE for k in keys}, 'coherence': P.NO},
    ]

    rng = random.Random(20260817)
    pools = {d.key: _value_pool(d) for d in P.DIMENSIONS}
    for _ in range(2000):
        cases.append({k: rng.choice(pools[k]) for k in keys})
    return cases


def _run_js(dims, cases, tmp_path):
    """Evaluate the shipped pass rule under node, once, for every case.

    Written to a file rather than passed via `node -e`: two thousand cases
    overflow the argv limit.
    """
    driver = tmp_path / 'parity.js'
    driver.write_text(
        f'const DIMS = {json.dumps(dims)};\n'
        f'{BV.PASS_RULE_JS}\n'
        f'const CASES = {json.dumps(cases)};\n'
        'console.log(JSON.stringify(CASES.map(c => sessionPasses(c))));\n'
    )
    proc = subprocess.run(
        ['node', str(driver)], capture_output=True, text=True, timeout=60,
    )
    assert proc.returncode == 0, f'node failed:\n{proc.stderr}'
    return json.loads(proc.stdout)


def test_js_pass_rule_agrees_with_python_on_every_case(tmp_path):
    """The verdict a grader sees must be the verdict Python would compute.

    Two implementations of one rule is a drift risk we accept (the page has no
    backend), so it is pinned rather than trusted.
    """
    cases = _parity_cases()
    got = _run_js(BV.dimensions_payload(), cases, tmp_path)
    expected = [P.session_passes(c) for c in cases]

    mismatches = [
        (c, e, g) for c, e, g in zip(cases, expected, got) if e != g
    ]
    assert not mismatches, (
        f'{len(mismatches)} of {len(cases)} cases disagree; first: '
        f'{mismatches[0]}'
    )


def test_js_pass_rule_ships_in_the_generated_page(tmp_path):
    """A rule that is tested but not shipped tests nothing."""
    out = tmp_path / 'index.html'
    BV.build(src=_fixture(tmp_path), out=str(out), flat_runs=[])
    assert BV.PASS_RULE_JS in out.read_text()


# ── The summary statistics on the comparison tab ────────────────────────

def _run_stats_js(body, tmp_path):
    """Run a snippet against the page's shipped stats helpers."""
    driver = tmp_path / 'stats.js'
    driver.write_text(
        f'const DIMS = {json.dumps(BV.dimensions_payload())};\n'
        f'{BV.PASS_RULE_JS}\n{BV.STATS_JS}\n{body}\n'
    )
    proc = subprocess.run(
        ['node', str(driver)], capture_output=True, text=True, timeout=60,
    )
    assert proc.returncode == 0, f'node failed:\n{proc.stderr}'
    return json.loads(proc.stdout)


def test_session_score_counts_only_applicable_dimensions(tmp_path):
    """The per-session percentage is over what was actually scorable.

    Dividing by eight instead would punish a session for dimensions that never
    arose, which is the same mistake as counting n/a as a failure.
    """
    desired = {d.key: d.desideratum for d in P.DIMENSIONS}
    cases = [
        {k: desired[k] for k in P.DIMENSION_KEYS},
        # Four at desideratum, four not -> 50% of eight applicable.
        {**{k: desired[k] for k in P.DIMENSION_KEYS},
         **{k: P.TO_SOME_EXTENT for k in list(P.DIMENSION_KEYS)[:4]}},
        # One scorable dimension, the rest never arose -> 100% of one.
        {**{k: P.NOT_APPLICABLE for k in P.DIMENSION_KEYS},
         'coherence': desired['coherence']},
        # Nothing scorable at all.
        {k: P.NOT_APPLICABLE for k in P.DIMENSION_KEYS},
        {k: '' for k in P.DIMENSION_KEYS},
    ]
    got = _run_stats_js(
        f'const C = {json.dumps(cases)};\n'
        'console.log(JSON.stringify(C.map(sessionScore)));', tmp_path)

    assert [g['pct'] for g in got] == [100.0, 50.0, 100.0, None, None]
    assert [g['applicable'] for g in got] == [8, 8, 1, 0, 0]
    # 'to some extent' is scorable-and-failing, not excluded — the mistake that
    # would make the first two cases both read 100%.
    assert got[1]['at'] == 4


def test_persona_balance_lists_personas_with_nothing_graded(tmp_path):
    """A persona you have not touched must appear with a zero bar.

    Dropping it is the one failure that defeats the chart's whole purpose: the
    persona you most need to grade next is the one with no rows to count.
    """
    personas = ['average', 'capable', 'error_prone', 'non_responder',
                'probe_resistant', 'struggler']
    rows = ([{'p': 'average'}] * 5 + [{'p': 'capable'}] * 2
            + [{'p': 'struggler'}] * 5)
    got = _run_stats_js(
        f'console.log(JSON.stringify(personaBalance({json.dumps(rows)}, '
        f'{json.dumps(personas)})));', tmp_path)

    assert [g['persona'] for g in got] == personas
    assert [g['n'] for g in got] == [5, 2, 0, 0, 0, 5]
    # Deficit is measured against the most-graded persona, so "all bars level"
    # is the same statement as "every deficit is zero".
    assert [g['deficit'] for g in got] == [0, 3, 5, 5, 5, 0]
    assert all(g['target'] == 5 for g in got)


def test_persona_balance_of_an_empty_set_is_all_zeroes(tmp_path):
    personas = ['average', 'capable']
    got = _run_stats_js(
        f'console.log(JSON.stringify(personaBalance([], '
        f'{json.dumps(personas)})));', tmp_path)
    assert [g['n'] for g in got] == [0, 0]
    assert [g['deficit'] for g in got] == [0, 0]


def test_non_applicable_rubric_items_read_as_na_not_zero(tmp_path):
    """A rubric item that did not apply carries score 0.0 in the result JSON
    and is excluded from the mean. Printing that 0.00 puts three apparent
    zeroes beside a 97% headline and reads as the tutor having failed something
    it was never asked to do — the same error as counting n/a against a human
    grader, which the pass rule is careful not to make.
    """
    items = [
        {'sc': 0.9, 'ap': True},    # scored
        {'sc': 0.0, 'ap': True},    # a real zero — must still read as 0.00
        {'sc': 0.0, 'ap': False},   # did not apply, stored as 0.0
        {'sc': None, 'ap': True},   # nothing recorded
    ]
    got = _run_stats_js(
        f'console.log(JSON.stringify({json.dumps(items)}.map(rubricDisplay)));',
        tmp_path)

    assert [g['na'] for g in got] == [False, False, True, True]
    assert [g['text'] for g in got] == ['0.90', '0.00', 'n/a', 'n/a']
    # An n/a item draws no bar; a genuine 0.00 also draws none but is not n/a.
    assert [g['width'] for g in got] == [90.0, 0.0, 0.0, 0.0]


def test_pass_rates_are_null_rather_than_zero_for_an_empty_set(tmp_path):
    """0% would assert the tutor failed everything. Nothing was measured."""
    got = _run_stats_js(
        'console.log(JSON.stringify([passRates([]), passRates('
        '[{h:true,j:false},{h:true,j:true},{h:false,j:true},{h:false,j:true}])]));',
        tmp_path)
    assert got[0] == {'n': 0, 'mine': None, 'judge': None}
    assert got[1] == {'n': 4, 'mine': 50.0, 'judge': 75.0}


# ── Coverage of the data itself ─────────────────────────────────────────

def test_runs_list_covers_every_result_location():
    """A new eval cycle must not land on disk and stay off the page.

    This is the failure that made the page show 580 of 860 sessions: seven
    cycle directories existed and were never added to RUNS. Cycle 6 was a
    second, quieter instance of the same bug — its result files sit at the top
    of the results tree rather than in a subdirectory of their own, so a check
    that only walked directories would have declared the page complete while
    sixty sessions stayed invisible. The empty string is how RUNS spells "the
    top level", so it is checked as one more location.
    """
    src = Path(BV.SRC)
    if not src.is_dir():
        pytest.skip(f'no local results at {src}')

    on_disk = {
        d.name for d in src.iterdir()
        if d.is_dir() and any(d.glob('*.json'))
    }
    if any(src.glob('*.json')):
        on_disk.add('')

    listed = {sub for sub, _label in BV.RUNS}
    assert not (on_disk - listed), (
        f'result locations missing from build_viewer.RUNS: '
        f'{sorted(on_disk - listed)}'
    )


def test_declared_flat_runs_exist_on_disk():
    """A result set named in FLAT_RUNS but absent from disk contributes nothing
    and says nothing about it — the page would just be quietly short."""
    for sub, label in BV.FLAT_RUNS:
        path = Path(BV.RESULTS) / sub
        if not path.is_dir():
            pytest.skip(f'{label}: {path} not present in this checkout')
        assert any(path.glob('*.json')), f'{label}: no result JSONs in {path}'


def test_mt100_board_is_on_the_page():
    """The 18-arm, 100-scenario board is the newest result set and the one most
    worth grading. It lives outside the fixcheck cycle tree, in a flat directory
    of one JSON per arm, so the cycle-directory walk alone never reaches it."""
    if not (Path(BV.RESULTS) / 'mt100').is_dir():
        pytest.skip('mt100 results not present in this checkout')

    sessions = BV.collect()
    mt100 = [s for s in sessions if s['run'].endswith('mt100_18arm_board')]

    assert len(mt100) == 1800, f'expected 18 arms x 100 scenarios, got {len(mt100)}'
    assert len({s['m'] for s in mt100}) == 18
    assert len({s['s'] for s in mt100}) == 100
    # The grading UI needs a judge verdict to compare against.
    assert all(s['rp'] is not None for s in mt100)


def test_every_session_on_the_page_has_a_unique_key():
    """Grades are stored against `k`. A collision would silently overwrite one
    session's verdict with another's."""
    src = Path(BV.SRC)
    if not src.is_dir():
        pytest.skip(f'no local results at {src}')

    keys = [s['k'] for s in BV.collect()]
    dupes = {k for k in keys if keys.count(k) > 1}
    assert not dupes, f'duplicate session keys: {sorted(dupes)[:5]}'


# ── The generated page ──────────────────────────────────────────────────

def _fixture(tmp_path):
    """Two sessions in the real result shape: one the judge passed, one not."""
    src = tmp_path / 'results'
    run = src / '_cycle0_baseline'
    run.mkdir(parents=True)

    def session(sid, passed, mean):
        return {
            'scenario_id': sid, 'persona': 'average', 'subject': 'math',
            'lesson_id': 1141, 'sim_reason': 'exit_ticket', 'passed': passed,
            'sim_turns': 12, 'error': None,
            'transcript': [
                {'role': 'tutor', 'phase': 'engage', 'content': 'Hello.'},
                {'role': 'student', 'phase': None, 'content': 'Hi.'},
            ],
            'rubric_result': {
                'mean_score': mean, 'pass_threshold': 0.6, 'passed': passed,
                'items': [{'item': 'Teaches rather than quizzes.',
                           'score': mean, 'applicable': True,
                           'reasoning': 'Explains before asking.'}],
            },
        }

    (run / 'test-model.json').write_text(json.dumps({'results': [
        session('scenario_a', True, 0.82),
        session('scenario_b', False, 0.41),
    ]}))
    return str(src)


def test_generated_page_carries_the_grading_surface(tmp_path):
    out = tmp_path / 'index.html'
    BV.build(src=_fixture(tmp_path), out=str(out), flat_runs=[])
    html = out.read_text()

    # The three new views the grading workflow needs.
    for view in ('grade', 'sxs', 'agreement'):
        assert f'data-v="{view}"' in html, f'no {view} tab on the page'

    # The taxonomy travels with the page rather than being fetched.
    assert 'const DIMS =' in html
    assert 'mistake_identification' in html
    # Every dimension's guidance is present, so a grader reads the same
    # instructions the dashboard shows.
    for dim in P.DIMENSIONS:
        assert dim.session_guidance[:40] in html


def test_generated_page_has_no_network_references(tmp_path):
    """The page's defining property: one file, opens anywhere, calls nothing."""
    out = tmp_path / 'index.html'
    BV.build(src=_fixture(tmp_path), out=str(out), flat_runs=[])
    html = out.read_text()

    for bad in ('src="http', 'href="http', 'fetch(', 'XMLHttpRequest'):
        assert bad not in html, f'page reaches the network via {bad!r}'


def test_model_counts_group_graded_sessions_by_model(tmp_path):
    """The model dropdown's labels carry their own session counts.

    A model with nothing graded is absent by design, and that is the opposite
    of the persona chart's rule one function above. The two lists answer
    different questions: personas are a worklist to level out, so a zero must
    be visible; models are scopes to compare, and an empty scope shows nothing
    but zeroes and dashes if you can select it.
    """
    sessions = ([{'m': 'qwen3-30b'}] * 4 + [{'m': 'deepseek-v3.1'}] * 2
                + [{'m': 'gemini-2.5-flash'}])
    got = _run_stats_js(
        f'console.log(JSON.stringify(modelCounts({json.dumps(sessions)})));',
        tmp_path)

    assert [g['model'] for g in got] == ['deepseek-v3.1', 'gemini-2.5-flash',
                                         'qwen3-30b']
    assert [g['n'] for g in got] == [2, 1, 4]


def test_model_counts_of_an_empty_set_is_empty(tmp_path):
    got = _run_stats_js('console.log(JSON.stringify(modelCounts([])));',
                        tmp_path)
    assert got == []


def test_me_vs_judge_tab_filters_by_model(tmp_path):
    """The comparison tab scopes to one model.

    Without it the pass rates on that tab are a single pooled number across
    every model in the run, which is the one figure that cannot answer "does
    the judge agree with me about THIS model".
    """
    out = tmp_path / 'index.html'
    BV.build(src=_fixture(tmp_path), out=str(out), flat_runs=[])
    html = out.read_text()

    assert 'id="x-model"' in html, 'no model filter on the me-vs-judge tab'
    # The filter has to reach the figures, not just the session list: the
    # summary, the session dropdown and the persona chart all read it.
    for fn in ('drawSxsSummary', 'fillSxsSel', 'personaChart'):
        assert fn in html
    assert "v('x-model')" in html
