# Generated by Django 6.0.2 on 2026-02-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_curriculumupload_steps_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('review', 'Review'), ('media_processing', 'Media Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
