# Generated by Django 6.0.2 on 2026-02-24 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_membership_role_alter_staffinvitation_role'),
        ('dashboard', '0004_alter_curriculumupload_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingMaterialUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('subject_name', models.CharField(max_length=100)),
                ('grade_level', models.CharField(blank=True, max_length=10)),
                ('material_type', models.CharField(choices=[('textbook', 'Textbook'), ('reference', 'Reference'), ('worksheet', 'Worksheet'), ('notes', 'Notes'), ('other', 'Other')], default='textbook', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('extracted_text_length', models.IntegerField(default=0)),
                ('chunks_created', models.IntegerField(default=0)),
                ('processing_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_material_uploads', to='accounts.institution')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_material_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
