# Generated by Django 6.0.2 on 2026-02-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_increase_grade_level_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingmaterialupload',
            name='figures_extracted',
            field=models.IntegerField(default=0),
        ),
    ]
