# Generated by Django 6.0.2 on 2026-02-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_figures_extracted_db_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumupload',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
