# Generated by Django 6.0.2 on 2026-02-28 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_copy_branding_to_platformconfig'),
        ('dashboard', '0011_add_is_cancelled_to_curriculumupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumupload',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Null = platform-wide curriculum upload', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_uploads', to='accounts.institution'),
        ),
    ]
