# Generated by Django 6.0.2 on 2026-03-01 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_copy_branding_to_platformconfig'),
        ('dashboard', '0012_alter_curriculumupload_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingmaterialupload',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Null = platform-wide teaching material', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_material_uploads', to='accounts.institution'),
        ),
    ]
