# Generated by Django 6.0.2 on 2026-04-28 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_drop_dead_fields'),
        ('dashboard', '0016_feedback_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Monday of the week this assignment covers.')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional teacher message — shown to students with the assignment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_assignments', to='curriculum.course')),
                ('lessons', models.ManyToManyField(blank=True, help_text='Lessons due this week.', related_name='weekly_assignments', to='curriculum.lesson')),
            ],
            options={
                'verbose_name': 'Weekly assignment',
                'verbose_name_plural': 'Weekly assignments',
                'ordering': ['-week_start'],
                'unique_together': {('course', 'week_start')},
            },
        ),
    ]
