# Generated by Django 6.0.2 on 2026-04-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_weeklyassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackreport',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Optional real-pixel screenshot attached by the user when submitting.', null=True, upload_to='feedback_screenshots/'),
        ),
    ]
