# Generated by Django 6.0.2 on 2026-05-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_teaching_material_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumupload',
            name='subject_code',
            field=models.CharField(blank=True, default='', help_text='Canonical SubjectCode (geography, mathematics, ...) chosen from the upload-form dropdown. Empty on uploads predating the dropdown rollout.', max_length=32),
        ),
    ]
