# Generated by Django 6.0.2 on 2026-09-12 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_add_backup_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='active_marker',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddConstraint(
            model_name='backupjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('active_marker',), name='dashboard_one_active_backup'),
        ),
    ]
