# Generated by Django 6.0.2 on 2026-09-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_backup_job_single_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='include_media',
            field=models.BooleanField(default=True),
        ),
    ]
