# Generated by Django 6.0.2 on 2026-09-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_backup_job_include_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='archive_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
