# Generated by Django 6.0.2 on 2026-09-13 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_backup_job_archive_checksum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoreJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('backup', 'Existing backup'), ('upload', 'Uploaded archive')], default='backup', max_length=10)),
                ('source_key', models.CharField(blank=True, max_length=500)),
                ('include_media', models.BooleanField(default=False)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('preflight', models.JSONField(blank=True, default=dict)),
                ('safety_backup_key', models.CharField(blank=True, max_length=500)),
                ('rds_snapshot_id', models.CharField(blank=True, max_length=255)),
                ('task_arn', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(blank=True, max_length=120)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('active_marker', models.BooleanField(default=True, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_jobs', to=settings.AUTH_USER_MODEL)),
                ('source_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restores', to='dashboard.backupjob')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status'], name='dashboard_r_created_d16912_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('active_marker',), name='dashboard_one_active_restore')],
            },
        ),
    ]
