# Generated by Django 6.0.2 on 2026-08-09 03:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0002_add_roster_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestate',
            name='enrolled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicestate',
            name='sync_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='SyncOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('session', 'Tutoring session + turns'), ('exit_ticket', 'Exit ticket attempt'), ('progress', 'Lesson progress')], max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('server_user_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting to send'), ('sent', 'Delivered'), ('failed', 'Given up')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, help_text='Backoff gate. The worker skips rows until this passes.', null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'sync outbox',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='desktop_syn_status_9aac17_idx')],
            },
        ),
    ]
