# Generated by Django 6.0.2 on 2026-02-13 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, choices=[('anse_boileau', 'Anse Boileau Secondary'), ('anse_royale', 'Anse Royale Secondary'), ('belonie', 'Belonie Secondary'), ('beau_vallon', 'Beau Vallon Secondary'), ('english_river', 'English River Secondary'), ('la_digue', 'La Digue Secondary'), ('mont_fleuri', 'Mont Fleuri Secondary'), ('perseverance', 'Perseverance Secondary'), ('pointe_larue', 'Pointe Larue Secondary'), ('plaisance', 'Plaisance Secondary'), ('praslin', 'Praslin Secondary'), ('other', 'Other')], help_text="Student's school", max_length=50)),
                ('grade_level', models.CharField(blank=True, choices=[('S1', 'Secondary 1'), ('S2', 'Secondary 2'), ('S3', 'Secondary 3'), ('S4', 'Secondary 4'), ('S5', 'Secondary 5')], help_text='Current grade level', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
