# Generated by Django 6.0.2 on 2026-02-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staffinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff (Teacher/Admin)'), ('student', 'Student')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffinvitation',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff (Teacher/Admin)'), ('student', 'Student')], default='staff', max_length=20),
        ),
    ]
