# Generated by Django 6.0.2 on 2026-02-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_institution_accent_color_institution_custom_css_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schools', models.JSONField(default=list)),
                ('grades', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Configuration',
            },
        ),
        migrations.RemoveField(
            model_name='institution',
            name='custom_css',
        ),
    ]
