# Generated by Django 6.0.2 on 2026-02-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_membership_role_alter_staffinvitation_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='secondary_color',
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='accent_color',
            field=models.CharField(default='#FFE66D', max_length=7),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='platform_logos/'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='platform_name',
            field=models.CharField(default='AI Tutor', max_length=255),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='primary_color',
            field=models.CharField(default='#E8590C', max_length=7),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='secondary_color',
            field=models.CharField(default='#4ECDC4', max_length=7),
        ),
    ]
