# Generated by Django 6.0.2 on 2026-04-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_competency_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='teachers_can_edit_content',
            field=models.BooleanField(default=False, help_text='If False, teachers can only view content and reports — they cannot edit, publish, regenerate, delete, or upload curriculum. Super admins always have full access.'),
        ),
    ]
