# Generated by Django 6.0.2 on 2026-04-27 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_student_id_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='session_mode',
            field=models.CharField(choices=[('shared_device', 'Shared device (paired sessions)'), ('individual', 'Individual accounts & devices')], default='shared_device', help_text="How students take lessons in this school. 'shared_device' lets paired students share a device — students can only add a pre-approved groupmate to their session. 'individual' hides the add-student button entirely.", max_length=20),
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Teacher-readable label, e.g., 'Pair A' or 'Group 1'.", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='When False, the group is archived and ignored by the session-add gate.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_groups', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='accounts.institution')),
                ('students', models.ManyToManyField(blank=True, help_text='Students in this group/pair.', related_name='student_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['institution', 'name'],
                'unique_together': {('institution', 'name')},
            },
        ),
    ]
