# Generated by Django 6.0.2 on 2026-06-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_locale_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='grade_level',
            field=models.CharField(blank=True, help_text="Current grade level. Country-specific and config-driven via PlatformConfig.grades (Seychelles 'S1'–'S5', Mozambique '8ª Classe', …), so it is not constrained to a fixed choice set. Sized to match the other grade_level fields in the codebase.", max_length=64),
        ),
    ]
