# Generated by Django 6.0.2 on 2026-07-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_seed_pt_mz_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='tutor_mode',
            field=models.CharField(choices=[('auto', 'Automatic — use the internet when available'), ('offline', 'Always use the offline tutor'), ('online', 'Always use the online tutor')], default='auto', help_text='Which tutor to use when more than one is available. AUTO prefers the online model when it is reachable and falls back to the offline one, so a dropped connection does not end the lesson.', max_length=10),
        ),
    ]
