# Generated by Django 6.0.2 on 2026-09-06 18:23

import ai_tutor.apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_add_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('default_locale', models.CharField(choices=[('en-us', '🇸🇨 Seychelles — English'), ('pt-mz', '🇲🇿 Moçambique — Português'), ('fr', '🇫🇷 Français'), ('sw', '🇹🇿 Kiswahili')], default='en-us', help_text='Default UI language for schools created in this country.', max_length=10)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden countries never appear in a school or country list.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff (Teacher/Admin)'), ('school_admin', 'School Admin'), ('student', 'Student')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffinvitation',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff (Teacher/Admin)'), ('school_admin', 'School Admin'), ('student', 'Student')], default='staff', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='country',
            field=models.ForeignKey(default=ai_tutor.apps.accounts.models.default_country, on_delete=django.db.models.deletion.PROTECT, related_name='institutions', to='accounts.country'),
        ),
        migrations.CreateModel(
            name='CountryMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['country', 'user'],
                'unique_together': {('user', 'country')},
            },
        ),
    ]
