# Generated by Django 6.0.2 on 2026-09-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_add_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='prefers_answer_picker',
            field=models.BooleanField(default=False, help_text='Show tappable A-D answer buttons instead of the typing box whenever the tutor asks a multiple-choice question.'),
        ),
    ]
