# Generated by Django 6.0.2 on 2026-09-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_backfill_seychelles'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso_code',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2. The account-request form matches on this, and the flag emoji is derived from it.', max_length=2, null=True, unique=True),
        ),
    ]
