# Generated by Django 6.0.2 on 2026-02-12 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('objective', models.TextField(help_text='What the student will learn/be able to do')),
                ('estimated_minutes', models.PositiveIntegerField(default=15, help_text='Estimated time to complete')),
                ('mastery_rule', models.CharField(choices=[('streak_3', '3 correct in a row'), ('streak_5', '5 correct in a row'), ('pass_quiz', 'Pass exit quiz (80%+)'), ('complete_all', 'Complete all steps')], default='streak_3', max_length=20)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('grade_level', models.CharField(blank=True, help_text="e.g., 'Grade 3', 'High School', 'Adult'", max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.institution')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LessonStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('step_type', models.CharField(choices=[('teach', 'Teaching'), ('worked_example', 'Worked Example'), ('practice', 'Practice Problem'), ('quiz', 'Quiz Question'), ('summary', 'Summary')], default='teach', max_length=20)),
                ('teacher_script', models.TextField(help_text='What the AI tutor should say/explain')),
                ('question', models.TextField(blank=True, help_text='The question to ask (for practice/quiz steps)')),
                ('answer_type', models.CharField(choices=[('none', 'No response needed'), ('free_text', 'Free Text'), ('multiple_choice', 'Multiple Choice'), ('short_numeric', 'Numeric Answer'), ('true_false', 'True/False')], default='none', max_length=20)),
                ('choices', models.JSONField(blank=True, help_text="For MCQ: list of choices, e.g., ['A', 'B', 'C', 'D']", null=True)),
                ('expected_answer', models.TextField(blank=True, help_text='The correct answer (text or JSON for complex answers)')),
                ('rubric', models.TextField(blank=True, help_text='Grading rubric for free-text answers (used by LLM)')),
                ('hint_1', models.TextField(blank=True)),
                ('hint_2', models.TextField(blank=True)),
                ('hint_3', models.TextField(blank=True)),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Max attempts before showing answer')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='curriculum.lesson')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='curriculum.course')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.unit'),
        ),
    ]
