# Generated by Django 6.0.2 on 2026-02-26 14:25

from django.db import migrations


def set_existing_content_status(apps, schema_editor):
    """Set content_status='ready' for lessons that already have >=5 steps."""
    Lesson = apps.get_model('curriculum', 'Lesson')
    from django.db.models import Count

    lessons_with_content = Lesson.objects.annotate(
        step_count=Count('steps')
    ).filter(step_count__gte=5)

    updated = lessons_with_content.update(content_status='ready')
    if updated:
        print(f"  Set {updated} existing lessons to content_status='ready'")


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_add_content_status_to_lesson'),
    ]

    operations = [
        migrations.RunPython(set_existing_content_status, migrations.RunPython.noop),
    ]
