# Generated by Django 6.0.2 on 2026-02-28 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_copy_branding_to_platformconfig'),
        ('curriculum', '0005_set_existing_lesson_content_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Null = platform-wide course visible to all schools', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.institution'),
        ),
    ]
