# Generated by Django 6.0.2 on 2026-03-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_add_concept_tag_to_lessonstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='grade_level',
            field=models.CharField(blank=True, help_text="Target grade level(s), e.g. 'S1', 'S1,S2'. Empty = visible to all grades in the course.", max_length=50),
        ),
    ]
