# Generated by Django 6.0.2 on 2026-04-14 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_seed_seychelles_context'),
        ('dashboard', '0014_cascade_delete_uploads_with_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='curriculum_upload',
            field=models.ForeignKey(blank=True, help_text='The curriculum upload that created this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to='dashboard.curriculumupload'),
        ),
    ]
