# Generated by Django 6.0.2 on 2026-04-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0013_group_lessons_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject_type',
            field=models.CharField(blank=True, choices=[('math', 'Math'), ('science', 'Science'), ('humanities', 'Humanities'), ('language', 'Language'), ('other', 'Other')], default='', help_text='Canonical subject classification. Drives is_math and subject-specific tutor rules. Empty falls back to the legacy MATH_KEYWORDS title heuristic.', max_length=20),
        ),
    ]
