# Generated by Django 6.0.2 on 2026-04-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0018_drop_course_generation_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstep',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Required'), (2, 'Core'), (3, 'Enrichment')], default=1, help_text='Step priority for runtime step selection. 1=required (always included), 2=core (included by default), 3=enrichment (dropped on short sessions). Legacy steps default to 1 so existing lessons render unchanged.'),
        ),
    ]
