# Generated by Django 6.0.2 on 2026-05-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0021_lesson_content_status_with_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade_levels',
            field=models.JSONField(blank=True, default=list, help_text="Normalised list of secondary years (e.g. ['S3'] or ['S1','S2','S3','S4','S5']). Used for material-sharing matches between school and platform-wide courses."),
        ),
        migrations.AddField(
            model_name='course',
            name='subject_code',
            field=models.CharField(blank=True, choices=[('mathematics', 'Mathematics'), ('geography', 'Geography'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('english', 'English'), ('french', 'French'), ('history', 'History'), ('computer_science', 'Computer Science'), ('other', 'Other')], default='', help_text='Canonical subject for cross-institution material sharing. Required for new courses; legacy rows backfilled via `python manage.py backfill_course_subjects`.', max_length=32),
        ),
    ]
