# Generated by Django 6.0.2 on 2026-05-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0023_course_tutoring_images_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstep',
            name='judge_outputs',
            field=models.JSONField(blank=True, default=dict, help_text='Content-judge verdicts keyed by judge name (factual_step, ...)'),
        ),
    ]
