# Generated by Django 6.0.2 on 2026-05-18 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0026_add_content_edit_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstep',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the step was marked as reviewed by a human.', null=True),
        ),
        migrations.AddField(
            model_name='lessonstep',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Teacher who marked this step as reviewed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
