# Generated by Django 6.0.2 on 2026-05-24 17:07
# Manually edited 2026-05-24: added VectorExtension() + vendor-gated
# HNSW index. See memory/pgvector_migration_plan.md (Phase 3).

import apps.curriculum.vector_field
from django.db import migrations, models


# 2026-05-25: replaced ``from pgvector.django import VectorExtension``
# + ``VectorExtension()`` with the vendor-gated RunPython below. The
# VectorExtension operation class is missing the ``hints`` attribute
# Django 6.0.2 requires on migration operations, so it crashes the
# migrate command on Postgres. We don't need its features (it only
# runs CREATE EXTENSION IF NOT EXISTS) — RunPython gives us the same
# behaviour without the broken class.
def _enable_vector_extension(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector;")


def _drop_vector_extension(apps, schema_editor):
    # Intentionally a no-op on reverse — dropping the extension would
    # break every other table that has a vector column, and the
    # extension is harmless to leave installed.
    return


# HNSW index: pgvector's similarity-search index using cosine distance.
# Cosine matches the metric the sentence-transformers all-MiniLM-L6-v2
# embeddings were originally trained for, and matches what the prior
# ChromaDB implementation used (the default for SentenceTransformer
# embeddings). m=16 + ef_construction=64 are pgvector defaults — fine
# for the expected scale (a few thousand chunks per institution).
_HNSW_INDEX_NAME = 'curriculum_chunk_embedding_hnsw'
_CREATE_HNSW_SQL = (
    f"CREATE INDEX IF NOT EXISTS {_HNSW_INDEX_NAME} "
    f"ON curriculum_curriculumchunk "
    f"USING hnsw (embedding vector_cosine_ops) "
    f"WITH (m = 16, ef_construction = 64);"
)
_DROP_HNSW_SQL = f"DROP INDEX IF EXISTS {_HNSW_INDEX_NAME};"


def _add_hnsw_index(apps, schema_editor):
    """Create the HNSW vector index on Postgres only.

    Skipped on SQLite + other backends (no pgvector). On those backends
    the ``embedding`` column falls back to TEXT and similarity search
    is not supported anyway.
    """
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(_CREATE_HNSW_SQL)


def _drop_hnsw_index(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(_DROP_HNSW_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0028_course_prerequisites_enabled'),
    ]

    operations = [
        # ``CREATE EXTENSION IF NOT EXISTS vector;`` on Postgres; no-op
        # on SQLite / MySQL. Vendor-gated RunPython (see top of file).
        migrations.RunPython(_enable_vector_extension, _drop_vector_extension),
        migrations.CreateModel(
            name='CurriculumChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The chunk text. Used as the source for embeddings + as the retrieved evidence string.')),
                ('embedding', apps.curriculum.vector_field.VectorField(dimensions=384, help_text='sentence-transformers all-MiniLM-L6-v2 vector. ``text`` column on SQLite (no vector ops).')),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('institution_id', models.IntegerField(db_index=True, help_text='0 = platform-wide (normalised). Otherwise an accounts.Institution PK. Not a FK — kept loose so chunks survive institution deletes.')),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('grade_level', models.CharField(blank=True, default='', max_length=64)),
                ('section', models.CharField(blank=True, default='', max_length=512)),
                ('chunk_type', models.CharField(blank=True, default='', help_text='content / objective / teaching_strategy / assessment / general / exam_question / marking_scheme / figure_description', max_length=64)),
                ('source_file', models.CharField(blank=True, default='', max_length=512)),
                ('upload_id', models.IntegerField(blank=True, db_index=True, help_text='dashboard.TeachingMaterialUpload or curriculum.CurriculumUpload PK. Loose link.', null=True)),
                ('source_type', models.CharField(blank=True, default='', help_text='teaching_material / question_bank / curriculum', max_length=64)),
                ('material_type', models.CharField(blank=True, default='', help_text='textbook / worksheet / question_bank / reference / notes / other', max_length=64)),
                ('material_title', models.CharField(blank=True, default='', max_length=512)),
                ('question_number', models.IntegerField(blank=True, null=True)),
                ('question_type', models.CharField(blank=True, default='', max_length=32)),
                ('has_answers', models.BooleanField(default=False)),
                ('year', models.CharField(blank=True, default='', max_length=16)),
                ('paper_number', models.CharField(blank=True, default='', max_length=64)),
                ('figure_type', models.CharField(blank=True, default='', max_length=64)),
                ('figure_page', models.IntegerField(blank=True, null=True)),
                ('figure_number', models.CharField(blank=True, default='', max_length=64)),
                ('figure_image_url', models.URLField(blank=True, default='', max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['institution_id', 'chunk_type'], name='cchunk_inst_type_idx'), models.Index(fields=['institution_id', 'subject', 'grade_level'], name='cchunk_inst_subj_grade_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution_id', 'content_hash'), name='curriculum_chunk_unique_per_institution')],
            },
        ),
        # HNSW vector index on the ``embedding`` column. Postgres only;
        # SQLite no-ops (similarity search isn't supported there).
        migrations.RunPython(_add_hnsw_index, _drop_hnsw_index),
    ]
