# Generated by Django 6.0.2 on 2026-06-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0030_course_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='seychellescontext',
            name='locale',
            field=models.CharField(db_index=True, default='en-us', help_text="Course locale this fact applies to (e.g. 'en-us', 'pt-mz'). Only injected into prompts for matching-locale content, so Seychelles facts don't leak into Mozambique courses.", max_length=10),
        ),
    ]
