# Generated by Django 6.0.2 on 2026-07-30 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_seed_pt_mz_terms'),
        ('curriculum', '0031_seychellescontext_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPackVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(help_text='Monotonic per institution. Devices refuse to go backwards.')),
                ('built_at', models.DateTimeField(auto_now_add=True)),
                ('schema_rev', models.CharField(help_text='Fingerprint of the migration graph this pack was built against. An importer on a different schema refuses.', max_length=40)),
                ('checksum', models.CharField(help_text='sha256 of the archive.', max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('lesson_count', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_pack_versions', to='accounts.institution')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('institution', 'version')},
            },
        ),
    ]
