# Generated by Django 6.0.2 on 2026-07-30 20:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.PositiveIntegerField(blank=True, help_text='Institution this device is bound to, set by the first content pack import. Packs from other institutions are refused — on a device there is no server to enforce the multi-tenancy invariant.', null=True)),
                ('pack_version', models.PositiveIntegerField(blank=True, help_text='Version of the imported content pack. NULL = not provisioned.', null=True)),
                ('pack_imported_at', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Stable identity for opt-in sync, so the server can tell two devices apart without knowing anything else about them.')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'device state',
                'verbose_name_plural': 'device state',
            },
        ),
    ]
