# Generated by Django 6.0.2 on 2026-08-09 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0001_add_device_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_user_id', models.PositiveIntegerField(help_text="The student's primary key on the SERVER. Never a local id.", unique=True)),
                ('username', models.CharField(max_length=150)),
                ('display_name', models.CharField(max_length=300)),
                ('grade_level', models.CharField(blank=True, default='', max_length=50)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('pack_version', models.PositiveIntegerField(blank=True, help_text='Pack version this entry last arrived in.', null=True)),
                ('local_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'roster entries',
                'ordering': ['display_name'],
            },
        ),
    ]
