# Generated by Django 6.0.2 on 2026-08-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0003_add_sync_outbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestate',
            name='access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='devicestate',
            name='refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='devicestate',
            name='server_url',
            field=models.URLField(blank=True, default='', help_text='Base URL of the server this device syncs to. Blank = this device is offline-only.', max_length=255),
        ),
        migrations.AddField(
            model_name='devicestate',
            name='server_user_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicestate',
            name='server_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
