# Generated by Django 6.0.2 on 2026-02-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='engine_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
