# Generated by Django 6.0.2 on 2026-02-21 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_membership_role_alter_staffinvitation_role'),
        ('curriculum', '0003_lessonstep_curriculum_context_and_more'),
        ('tutoring', '0004_alter_exitticketquestion_explanation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique code, e.g., 'geo_identify_fault_types'", max_length=100)),
                ('name', models.CharField(help_text="Human-readable name, e.g., 'Identify types of geological faults'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this skill entails')),
                ('difficulty', models.CharField(choices=[('foundational', 'Foundational'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('difficulty_score', models.FloatField(default=0.5, help_text='Numeric difficulty 0.0 (easy) to 1.0 (hard)')),
                ('importance', models.FloatField(default=0.5, help_text='How critical this skill is (0.0 to 1.0)')),
                ('bloom_level', models.CharField(choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], default='understand', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags for categorization, e.g., ['plate_tectonics', 'geology']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='curriculum.course')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='accounts.institution')),
                ('lessons', models.ManyToManyField(blank=True, help_text='All lessons that teach or practice this skill', related_name='skills', to='curriculum.lesson')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Skills that should be mastered before this one', related_name='unlocks', to='tutoring.skill')),
                ('primary_lesson', models.ForeignKey(blank=True, help_text='The main lesson that teaches this skill', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_skills', to='curriculum.lesson')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='curriculum.unit')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['course', 'unit', 'name'],
                'unique_together': {('institution', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StudentSkillMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.FloatField(default=0.0, help_text='Current mastery level (0.0 to 1.0)')),
                ('state', models.CharField(choices=[('not_started', 'Not Started'), ('learning', 'Learning'), ('reviewing', 'Reviewing'), ('mastered', 'Mastered')], default='not_started', max_length=20)),
                ('last_practiced', models.DateTimeField(blank=True, help_text='When this skill was last practiced', null=True)),
                ('next_review_due', models.DateTimeField(blank=True, help_text='When this skill should be reviewed', null=True)),
                ('repetition_count', models.IntegerField(default=0, help_text='Number of successful reviews')),
                ('ease_factor', models.FloatField(default=2.5, help_text='SM-2 ease factor (1.3 to 3.0)')),
                ('interval_days', models.IntegerField(default=1, help_text='Current review interval in days')),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0, help_text='Current streak of correct answers')),
                ('best_streak', models.IntegerField(default=0)),
                ('first_learned', models.DateTimeField(blank=True, help_text='When the student first learned this skill', null=True)),
                ('last_correct', models.DateTimeField(blank=True, null=True)),
                ('last_incorrect', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mastery', to='tutoring.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_mastery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Skill Mastery',
                'verbose_name_plural': 'Student Skill Mastery Records',
                'ordering': ['-updated_at'],
                'unique_together': {('student', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='SkillPracticeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_type', models.CharField(choices=[('initial', 'Initial Learning'), ('retrieval', 'Retrieval Practice'), ('interleaved', 'Interleaved Practice'), ('review', 'Spaced Review'), ('remediation', 'Targeted Remediation')], default='initial', max_length=20)),
                ('was_correct', models.BooleanField()),
                ('quality', models.IntegerField(blank=True, help_text='Quality rating 0-5', null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('hints_used', models.IntegerField(default=0)),
                ('mastery_before', models.FloatField()),
                ('mastery_after', models.FloatField()),
                ('retention_estimate', models.FloatField(blank=True, help_text='Estimated retention at time of practice', null=True)),
                ('practiced_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.lessonstep')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_practice_logs', to='tutoring.tutorsession')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_logs', to='tutoring.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_practice_logs', to=settings.AUTH_USER_MODEL)),
                ('mastery_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_logs', to='tutoring.studentskillmastery')),
            ],
            options={
                'verbose_name': 'Skill Practice Log',
                'ordering': ['-practiced_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.FloatField(default=1.0, help_text='1.0 = essential, 0.5 = helpful, 0.0 = loosely related')),
                ('is_direct', models.BooleanField(default=True, help_text='True if this is an immediate prerequisite, False if transitive')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='curriculum.lesson')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='curriculum.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Prerequisite',
                'unique_together': {('lesson', 'prerequisite')},
            },
        ),
        migrations.CreateModel(
            name='StudentKnowledgeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_skills', models.IntegerField(default=0)),
                ('mastered_skills', models.IntegerField(default=0)),
                ('learning_skills', models.IntegerField(default=0)),
                ('average_mastery', models.FloatField(default=0.0)),
                ('average_retention', models.FloatField(default=0.0)),
                ('total_practice_time_minutes', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('current_streak_days', models.IntegerField(default=0)),
                ('longest_streak_days', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('total_xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_profiles', to='curriculum.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Knowledge Profile',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
