# Generated by Django 6.0.2 on 2026-03-06 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0007_tutorsession_flagging'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('emoji', models.CharField(default='', max_length=10)),
                ('category', models.CharField(choices=[('milestone', 'Milestone'), ('streak', 'Streak'), ('mastery', 'Mastery'), ('special', 'Special')], default='milestone', max_length=20)),
                ('trigger_type', models.CharField(choices=[('first_lesson', 'First Lesson Completed'), ('lessons_completed', 'Lessons Completed'), ('streak_days', 'Streak Days'), ('xp_threshold', 'XP Threshold'), ('level_reached', 'Level Reached'), ('perfect_score', 'Perfect Exit-Ticket Score'), ('exit_ticket_pass', 'Exit Ticket Passed')], max_length=30)),
                ('trigger_value', models.IntegerField(default=0)),
                ('xp_reward', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('is_seen', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='tutoring.achievement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('student', 'achievement')},
            },
        ),
    ]
