# Generated by Django 6.0.2 on 2026-04-18 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0013_session_time_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Guidance instruction for the tutor engine')),
                ('is_from_ai', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this guidance is currently applied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, help_text='Teacher who sent this, or null for Monitor AI', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidances', to='tutoring.tutorsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
