# Generated by Django 6.0.2 on 2026-04-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0014_teacher_guidance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlessonprogress',
            name='attempts_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of exit ticket attempts across all sessions for this lesson.'),
        ),
        migrations.AddField(
            model_name='studentlessonprogress',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, help_text='When the student most recently submitted the exit ticket.', null=True),
        ),
        migrations.AlterField(
            model_name='studentlessonprogress',
            name='best_score',
            field=models.FloatField(blank=True, help_text='Best exit-ticket score as a fraction in [0.0, 1.0]. Populated on every exit ticket submission. Monotonic (never demoted).', null=True),
        ),
    ]
