# Generated by Django 6.0.2 on 2026-04-25 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0018_backfill_session_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlessonprogress',
            name='last_completion_session',
            field=models.ForeignKey(blank=True, help_text='The session that earned mastery (or the most recent attempt session).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_progress_records', to='tutoring.tutorsession'),
        ),
        migrations.AddField(
            model_name='studentlessonprogress',
            name='last_completion_was_group',
            field=models.BooleanField(default=False, help_text='True when the last attempt session had multiple active participants (group lesson). Filterable for teacher reports.'),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='group_approval_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='group_approval_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='group_approval_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='not_required', max_length=20),
        ),
    ]
