# Generated by Django 6.0.2 on 2026-04-26 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_drop_dead_fields'),
        ('tutoring', '0020_drop_dead_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionturn',
            name='client_generated_at',
            field=models.DateTimeField(blank=True, help_text='Wall-clock time on the client when the turn was authored. Distinct from created_at (server-side ingest time).', null=True),
        ),
        migrations.AddField(
            model_name='sessionturn',
            name='generated_offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionturn',
            name='offline_model_id',
            field=models.CharField(blank=True, help_text='MobileInferenceModel.id used to generate this turn (if offline).', max_length=100),
        ),
        migrations.CreateModel(
            name='LessonPackVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('policy_json', models.JSONField(default=dict, help_text='State-machine policy for the on-device runner.')),
                ('content_snapshot', models.JSONField(default=dict, help_text='Frozen lesson + steps + exit ticket questions at this version.')),
                ('media_manifest', models.JSONField(blank=True, default=list, help_text='List of media URLs referenced by the pack (for client to download).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_versions_created', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_versions', to='curriculum.lesson')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lesson', '-version'], name='tutoring_le_lesson__b8bc92_idx')],
                'unique_together': {('lesson', 'version')},
            },
        ),
    ]
