# Generated by Django 6.0.2 on 2026-04-27 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_drop_dead_fields'),
        ('tutoring', '0021_mobile_api'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exitticket',
            options={'verbose_name': 'Exit Ticket / Summative', 'verbose_name_plural': 'Exit Tickets & Summatives'},
        ),
        migrations.AddField(
            model_name='exitticket',
            name='assessment_type',
            field=models.CharField(choices=[('exit_ticket', 'Exit Ticket (lesson-level)'), ('summative', 'Summative Exam (course-level)')], default='exit_ticket', max_length=20),
        ),
        migrations.AddField(
            model_name='exitticket',
            name='course',
            field=models.OneToOneField(blank=True, help_text="Set for assessment_type='summative'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summative_exam', to='curriculum.course'),
        ),
        migrations.AddField(
            model_name='exitticket',
            name='is_published',
            field=models.BooleanField(default=False, help_text="Summatives only — when False, students can't take the exam."),
        ),
        migrations.AddField(
            model_name='exitticket',
            name='question_bank_size',
            field=models.PositiveIntegerField(default=30, help_text='Target size of the question bank. 30 for exit tickets, 90 for summatives.'),
        ),
        migrations.AddField(
            model_name='exitticket',
            name='questions_per_attempt',
            field=models.PositiveIntegerField(default=10, help_text='How many questions a student sees per attempt. 10 for exit tickets, 30 for summatives.'),
        ),
        migrations.AlterField(
            model_name='exitticket',
            name='instructions',
            field=models.TextField(blank=True, default='Answer all questions. You need to pass the threshold to complete.'),
        ),
        migrations.AlterField(
            model_name='exitticket',
            name='lesson',
            field=models.OneToOneField(blank=True, help_text="Set for assessment_type='exit_ticket'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exit_ticket', to='curriculum.lesson'),
        ),
        migrations.AlterField(
            model_name='exitticket',
            name='passing_score',
            field=models.PositiveIntegerField(default=8, help_text='Minimum correct answers to pass.'),
        ),
        migrations.AlterField(
            model_name='exitticket',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Time limit in minutes (0 = no limit).'),
        ),
        migrations.AddConstraint(
            model_name='exitticket',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', True), ('lesson__isnull', False)), models.Q(('course__isnull', False), ('lesson__isnull', True)), _connector='OR'), name='exitticket_lesson_xor_course'),
        ),
    ]
