# Generated by Django 6.0.2 on 2026-04-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0023_attempt_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitticketattempt',
            name='purpose',
            field=models.CharField(choices=[('practice', 'Practice / lesson exit ticket'), ('baseline', 'Baseline (pre-course summative)'), ('final', 'Final (post-course summative)'), ('retake', 'Retake'), ('diagnostic', 'Diagnostic (pre-lesson assessment)')], default='practice', help_text="What this attempt counts as. Baseline + Final on a summative drive the dashboard's longitudinal competency view.", max_length=15),
        ),
    ]
