# Generated by Django 6.0.2 on 2026-04-28 19:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_emailverificationtoken_useremailstatus'),
        ('curriculum', '0017_course_generation_profile'),
        ('tutoring', '0024_alter_exitticketattempt_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCompetencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granularity', models.CharField(choices=[('lesson', 'Lesson'), ('skill', 'Skill')], max_length=10)),
                ('objective_text', models.TextField(help_text='The lesson objective or skill name at the moment of mastery.')),
                ('course_title_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('unit_title_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('lesson_title_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('skill_name_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('subject', models.CharField(blank=True, default='', max_length=20)),
                ('grade_level', models.CharField(blank=True, default='', max_length=10)),
                ('score', models.FloatField(blank=True, help_text='Best score 0.0–1.0 at the moment of earning (lesson granularity).', null=True)),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_records', to='accounts.institution')),
                ('source_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competency_records', to='curriculum.course')),
                ('source_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competency_records', to='curriculum.lesson')),
                ('source_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competency_records_earned', to='tutoring.tutorsession')),
                ('source_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competency_records', to='tutoring.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['student', '-earned_at'], name='tutoring_st_student_d89dbf_idx'), models.Index(fields=['student', 'granularity'], name='tutoring_st_student_352980_idx'), models.Index(fields=['institution', '-earned_at'], name='tutoring_st_institu_b2ef40_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('granularity', 'lesson'), ('source_lesson__isnull', False)), fields=('student', 'source_lesson'), name='unique_student_lesson_competency'), models.UniqueConstraint(condition=models.Q(('granularity', 'skill'), ('source_skill__isnull', False)), fields=('student', 'source_skill'), name='unique_student_skill_competency')],
            },
        ),
    ]
