# Generated by Django 6.0.2 on 2026-05-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0027_exitticketquestion_enabling_objective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionturn',
            name='judge_outputs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
