# Generated by Django 6.0.2 on 2026-05-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0029_turnspan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='is_synthetic',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this session was driven by the LLM-as-student simulator rather than a real student.'),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='sim_persona',
            field=models.CharField(blank=True, help_text="Persona key from apps/tutoring/student_sim/personas.py (e.g. 'struggler'). Empty for real sessions.", max_length=40),
        ),
    ]
