# Generated by Django 6.0.2 on 2026-05-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0030_add_synthetic_session_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitticketquestion',
            name='judge_outputs',
            field=models.JSONField(blank=True, default=dict, help_text='Content-judge verdicts keyed by judge name (exit_question, ...)'),
        ),
    ]
