# Generated by Django 6.0.2 on 2026-05-18 04:06
#
# Adds ExitTicketQuestion.content_quality_status (+ reviewed_by /
# reviewed_at) per task #215 — gives the dashboard a single field to
# read for the bulk-review + mark-reviewed flows, mirroring the field
# already on LessonStep.
#
# Data migration backfills content_quality_status from existing
# judge_outputs so rows that already ran through the exit_question
# judge don't surface as "unreviewed" in the new dashboard counts.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill_status_from_judge_outputs(apps, schema_editor):
    """Populate ExitTicketQuestion.content_quality_status from any
    pre-existing judge_outputs entry. Mirrors what the judge pipeline
    will start writing going forward."""
    ExitTicketQuestion = apps.get_model('tutoring', 'ExitTicketQuestion')
    ok = flagged = unrev = 0
    for q in ExitTicketQuestion.objects.iterator(chunk_size=500):
        jo = q.judge_outputs or {}
        verdict = jo.get('exit_question') or {}
        passed = verdict.get('passed')
        if passed is True:
            q.content_quality_status = 'auto_ok'
            ok += 1
        elif passed is False:
            q.content_quality_status = 'auto_flagged'
            flagged += 1
        else:
            # No judge output yet (or schema we don't recognise) —
            # leave as default 'unreviewed' from the AddField step.
            unrev += 1
            continue
        q.save(update_fields=['content_quality_status'])
    print(
        f"  [tutoring.0032] backfilled content_quality_status: "
        f"auto_ok={ok} auto_flagged={flagged} unreviewed={unrev}"
    )


def _backfill_noop_reverse(apps, schema_editor):
    """Reverse is a no-op — the AddField reversal drops the column
    entirely; no data to restore."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0031_add_exit_question_judge_outputs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exitticketquestion',
            name='content_quality_status',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('auto_ok', 'Auto-approved by judges'), ('auto_flagged', 'Needs human review'), ('human_approved', 'Human-approved'), ('human_edited', 'Human-edited')], default='unreviewed', help_text="Quality gate state for this question. Populated from judge_outputs by the exit_question judge at content-gen time and updated by the 'Mark as Reviewed' flow.", max_length=20),
        ),
        migrations.AddField(
            model_name='exitticketquestion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the question was marked as reviewed by a human.', null=True),
        ),
        migrations.AddField(
            model_name='exitticketquestion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Teacher who marked this question as reviewed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            _backfill_status_from_judge_outputs,
            _backfill_noop_reverse,
        ),
    ]
