# Generated by Django 6.0.2 on 2026-05-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0032_exitticketquestion_content_quality_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='engine_version',
            field=models.CharField(default='legacy', help_text="Which tutoring engine owns this session ('legacy' or 'v2'). Sticky across resumes — set at session start, not on every turn.", max_length=20),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='runtime_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
