# Generated by Django 6.0.2 on 2026-05-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0033_add_v2_runtime_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorsession',
            name='engine_version',
            field=models.CharField(blank=True, default='', help_text="Which tutoring engine owns this session ('legacy' or 'v2'). Sticky across resumes — set at session start by apps.tutoring.v2.routing.ensure_engine_version_set. Empty string = not yet decided (env-var picks at first entry-point call).", max_length=20),
        ),
    ]
