# Generated by Django 6.0.2 on 2026-05-26 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0034_add_current_question_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='InFlightQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question stem the tutor posed (verbatim).')),
                ('question_type', models.CharField(choices=[('mcq', 'mcq'), ('short_numeric', 'short_numeric'), ('short_answer', 'short_answer')], help_text='Selects the grading tier in apps.tutoring.simple_tutor.grader.', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('reference_answer', models.TextField(help_text='What the tutor would mark correct. For MCQ: the letter (A/B/C/D). For short_numeric: the numeric value. For short_answer: one canonical phrasing.')),
                ('source', models.CharField(choices=[('catalog', 'from <question_pool>'), ('inline_authored', 'authored by LLM in-line')], help_text='Whether the tutor used a question from <question_pool> or authored its own.', max_length=20)),
                ('catalog_question_id', models.IntegerField(blank=True, help_text='ExitTicketQuestion / LessonStep pk when source=catalog. Used for catalog cross-checks + analytics.', null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('posed_at', models.DateTimeField(auto_now_add=True)),
                ('posed_at_turn', models.ForeignKey(blank=True, help_text='The tutor SessionTurn whose pose_question call created this row. Audit trail.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tutoring.sessionturn')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='in_flight_question', to='tutoring.tutorsession')),
            ],
            options={
                'db_table': 'tutoring_inflightquestion',
            },
        ),
    ]
