# Generated by Django 6.0.2 on 2026-02-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_lesson_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstep',
            name='curriculum_context',
            field=models.JSONField(blank=True, help_text='Curriculum context from knowledge base. Structure:\n        {\n            "teaching_strategies": ["strategy 1", "strategy 2"],\n            "learning_objectives": ["objective 1"],\n            "assessment_criteria": ["criteria 1"],\n            "prerequisite_knowledge": ["prereq 1"],\n            "cross_curricular_links": ["link 1"],\n            "differentiation": {\n                "support": "For struggling students...",\n                "extension": "For advanced students..."\n            },\n            "resources_from_curriculum": ["resource 1"]\n        }\n        ', null=True),
        ),
        migrations.AddField(
            model_name='lessonstep',
            name='educational_content',
            field=models.JSONField(blank=True, help_text='Educational materials for this step. Structure:\n        {\n            "key_vocabulary": [\n                {"term": "...", "definition": "...", "example": "..."}\n            ],\n            "worked_example": {\n                "problem": "...",\n                "steps": [\n                    {"step": 1, "action": "...", "explanation": "..."}\n                ],\n                "final_answer": "..."\n            },\n            "formulas": [\n                {"name": "...", "formula": "...", "variables": {...}}\n            ],\n            "key_points": ["point 1", "point 2"],\n            "common_mistakes": ["mistake 1", "mistake 2"],\n            "real_world_connections": ["connection 1"],\n            "seychelles_context": "Local example or connection"\n        }\n        ', null=True),
        ),
        migrations.AddField(
            model_name='lessonstep',
            name='media',
            field=models.JSONField(blank=True, help_text='Media content for this step. Structure:\n        {\n            "images": [\n                {\n                    "url": "/media/lessons/...",\n                    "alt": "Description of image",\n                    "caption": "Figure 1: ...",\n                    "type": "diagram|photo|illustration|chart",\n                    "source": "generated|library|curriculum"\n                }\n            ],\n            "videos": [\n                {\n                    "url": "https://...",\n                    "title": "Video title",\n                    "duration_seconds": 120,\n                    "start_time": 0\n                }\n            ],\n            "audio": [\n                {\n                    "url": "/media/audio/...",\n                    "title": "Pronunciation guide"\n                }\n            ]\n        }\n        ', null=True),
        ),
        migrations.AddField(
            model_name='lessonstep',
            name='phase',
            field=models.CharField(blank=True, help_text='Pedagogical phase: engage, explore, explain, practice, evaluate', max_length=20),
        ),
    ]
