# Generated by Django 6.0.2 on 2026-02-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_lessonstep_curriculum_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_status',
            field=models.CharField(choices=[('empty', 'Empty'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='empty', help_text='Status of generated content for this lesson', max_length=20),
        ),
    ]
