# Generated by Django 6.0.2 on 2026-03-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_alter_course_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstep',
            name='concept_tag',
            field=models.CharField(blank=True, default='', help_text='Groups steps by concept — all steps teaching/practicing the same concept share a tag', max_length=200),
        ),
    ]
