# Generated by Django 6.0.2 on 2026-04-12 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_unit_grade_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeychellesContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('economic', 'Economic'), ('geographic', 'Geographic'), ('trade', 'Trade'), ('climate', 'Climate'), ('population', 'Population'), ('sustainable_dev', 'Sustainable Development'), ('os_map', 'OS Map Data'), ('industry', 'Industry')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='The factual content or data point')),
                ('subject_tags', models.JSONField(blank=True, default=list, help_text="Subjects this is relevant to, e.g. ['geography', 'economics']")),
                ('grade_levels', models.JSONField(blank=True, default=list, help_text="Applicable grade levels, e.g. ['S1', 'S2', 'S3']")),
                ('source', models.CharField(blank=True, help_text='Data source or attribution', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Seychelles context entries',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_quality',
            field=models.CharField(choices=[('tier_1', 'Tier 1 - Fully Resourced'), ('tier_2', 'Tier 2 - Syllabus + Exam'), ('tier_3', 'Tier 3 - Syllabus Only'), ('tier_4', 'Tier 4 - Framework Only')], default='tier_3', help_text='Content quality tier based on available source materials', max_length=10),
        ),
        migrations.AddField(
            model_name='lesson',
            name='enabling_objectives',
            field=models.JSONField(blank=True, default=list, help_text='List of enabling objectives this lesson covers'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher_approved',
            field=models.BooleanField(default=False, help_text='Teacher has reviewed and approved this content (required for tier_3/tier_4)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonstep',
            name='enabling_objective',
            field=models.CharField(blank=True, default='', help_text='The specific enabling objective this step addresses', max_length=500),
        ),
        migrations.AddField(
            model_name='unit',
            name='enabling_objectives',
            field=models.JSONField(blank=True, default=list, help_text='Unit-level enabling objectives — granular teaching steps from the syllabus'),
        ),
        migrations.AddField(
            model_name='unit',
            name='terminal_objectives',
            field=models.JSONField(blank=True, default=list, help_text='Unit-level terminal objectives — what students must achieve by end of unit'),
        ),
    ]
