# Generated by Django 6.0.2 on 2026-04-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_course_curriculum_upload_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='allow_group_mode',
            field=models.BooleanField(default=True, help_text='Whether students may complete this lesson together as a group.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='max_group_size',
            field=models.PositiveIntegerField(default=4, help_text='Maximum number of students allowed in a group session for this lesson.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=20, help_text='Estimated time to complete'),
        ),
    ]
