# Generated by Django 6.0.2 on 2026-04-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_group_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='group_requires_approval',
            field=models.BooleanField(default=False, help_text='When True, group sessions for this lesson are blocked until a teacher approves them. Prevents students adding many friends just to skip the lesson. See memory/group_lessons_v2_plan.md.'),
        ),
    ]
