# Generated by Django 6.0.2 on 2026-04-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_backfill_subject_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='mastery_rule',
        ),
    ]
