# Generated by Django 6.0.2 on 2026-04-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_drop_dead_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='generation_profile',
            field=models.CharField(choices=[('standard', 'Standard'), ('slow_learner', 'Slower / weaker learners (more figures, more MCQ/TF)'), ('advanced', 'Advanced (richer free-response, fewer hints)')], default='standard', help_text='Calibrates content generation. Slow learners get more visual scaffolding and a varied question-format mix; advanced gets richer free-response and fewer hints.', max_length=20),
        ),
    ]
