# Generated by Django 6.0.2 on 2026-04-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0017_course_generation_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='generation_profile',
        ),
    ]
