# Generated by Django 6.0.2 on 2026-04-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0019_lesson_step_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_student_duration_override',
            field=models.BooleanField(default=True, help_text='Whether students may pick their session duration via the chat-page picker. When False, sessions always use the teacher-configured lesson.estimated_minutes.'),
        ),
    ]
