# Generated by Django 6.0.2 on 2026-05-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0022_course_subject_code_grade_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tutoring_images_enabled',
            field=models.BooleanField(default=True, help_text='Whether the AI tutor may show or reference images during tutoring sessions. Off = pure text. Default on.'),
        ),
    ]
