# Generated by Django 6.0.2 on 2026-05-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0024_add_lesson_step_judge_outputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstep',
            name='content_quality_status',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('auto_ok', 'Auto-approved by judges'), ('auto_flagged', 'Needs human review'), ('human_approved', 'Human-approved'), ('human_edited', 'Human-edited')], default='unreviewed', help_text="Quality gate state. 'auto_flagged' means judges + regen couldn't fix the content — surfaces a 'Needs Human Review' badge in the lesson detail UI. See memory/content_quality_review_plan.md.", max_length=20),
        ),
    ]
