# Generated by Django 6.0.2 on 2026-05-15 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0025_add_step_content_quality_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('step', 'Lesson Step'), ('exit_question', 'Exit-Ticket Question'), ('image', 'Media Image')], help_text='Type of content edited', max_length=20)),
                ('content_id', models.PositiveIntegerField(help_text='PK of LessonStep / ExitTicketQuestion / MediaAsset')),
                ('before_payload', models.JSONField(blank=True, default=dict, help_text='Frozen state pre-edit (for diff + replay)')),
                ('after_payload', models.JSONField(blank=True, default=dict, help_text='Frozen state post-edit')),
                ('suggested_tags', models.JSONField(blank=True, default=list, help_text='Auto-derived tag suggestions from diff + judge_outputs')),
                ('error_tags', models.JSONField(blank=True, default=list, help_text='Teacher-confirmed tags. Defaults to suggested_tags.')),
                ('teacher_notes', models.TextField(blank=True, default='', help_text='Free-form note the teacher left about the edit.')),
                ('judge_outputs_at_edit', models.JSONField(blank=True, default=dict, help_text='judge_outputs snapshot at edit time (judge_predicts_edit analysis)')),
                ('source', models.CharField(choices=[('manual_edit', 'Manual edit (teacher typed)'), ('ai_regen_auto', 'AI regen (auto-review mode)'), ('ai_regen_prompt', 'AI regen (prompt mode)'), ('image_regen', 'Image regenerated')], default='manual_edit', help_text='How this edit was triggered', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(blank=True, help_text='Teacher who made the edit (null when system-driven)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_edit_events', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, help_text='Parent lesson — kept on SET_NULL so events survive course deletion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_edit_events', to='curriculum.lesson')),
            ],
            options={
                'verbose_name': 'Content Edit Event',
                'verbose_name_plural': 'Content Edit Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'content_id'], name='curriculum__content_dc3d7d_idx'), models.Index(fields=['lesson', '-created_at'], name='curriculum__lesson__0df1bc_idx'), models.Index(fields=['-created_at'], name='curriculum__created_e73316_idx')],
            },
        ),
    ]
