# Generated by Django 6.0.2 on 2026-05-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0027_lessonstep_reviewed_at_lessonstep_reviewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites_enabled',
            field=models.BooleanField(default=True, help_text='Whether lessons in this course enforce LessonPrerequisite gating. Off = all lessons unlocked regardless of prior mastery. Default on.'),
        ),
    ]
