# Generated by Django 6.0.2 on 2026-08-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0032_add_content_pack_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonstep',
            name='step_type',
            field=models.CharField(choices=[('warm_up', 'Warm-up'), ('teach', 'Teaching'), ('worked_example', 'Worked Example'), ('practice', 'Practice Problem'), ('quiz', 'Quiz Question'), ('summary', 'Summary')], default='teach', max_length=20),
        ),
    ]
