# Generated by Django 6.0.2 on 2026-09-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0034_add_warm_up_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='retired_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Set when a curriculum re-upload replaced this lesson. The row and all student records are kept; the lesson is unpublished and hidden from the course's lesson list.", null=True),
        ),
    ]
