# Generated by Django 6.0.2 on 2026-09-06 18:23

import ai_tutor.apps.accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_add_country'),
        ('curriculum', '0034_add_warm_up_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='country',
            field=models.ForeignKey(default=ai_tutor.apps.accounts.models.default_country, help_text="Which country's schools may see this course.", on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='accounts.country'),
        ),
        migrations.AlterField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(blank=True, help_text="Null = shared with every school in this course's COUNTRY. It used to mean every school on the platform; countries narrowed it. See accounts/tenancy.py.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.institution'),
        ),
    ]
