"""Rename Course.grade_levels → grade_levels_stored, in STATE ONLY.

`grade_levels` is now a property that parses `grade_level`
(memory/subject_grade_unification_plan.md step 3), so the field has to give up
the name. The column itself must not move: `db_column='grade_levels'` keeps it
exactly where it is, and SeparateDatabaseAndState with no database_operations
means no SQL runs at all.

Autogenerated makemigrations proposed RemoveField + AddField, which DROPS the
column and creates a new empty one — a rollback would then find the data gone.
The column is dropped in a later release, once this one has shipped without
writing to it.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('curriculum', '0036_backfill_math_subject_code')]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(model_name='course', name='grade_levels'),
                migrations.AddField(
                    model_name='course',
                    name='grade_levels_stored',
                    field=models.JSONField(
                        db_column='grade_levels',
                        default=list,
                        blank=True,
                        help_text=(
                            'Deprecated — read Course.grade_levels, which '
                            'parses grade_level.'
                        ),
                    ),
                ),
            ],
        ),
    ]
