"""Rename Course.subject_type → subject_type_stored, in STATE ONLY.

`subject_type` is now a property that maps `subject_code`
(memory/subject_grade_unification_plan.md step 4), so the field has to give up
the name. The column itself must not move: `db_column='subject_type'` keeps it
exactly where it is, and SeparateDatabaseAndState with no database_operations
means no SQL runs at all.

Same shape and same reason as 0037: autogenerated makemigrations proposes
RemoveField + AddField, which DROPS the column and creates a new empty one, so
a rollback would find the data gone. The column is dropped in a later release,
once this one has shipped without writing to it.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('curriculum', '0037_deprecate_course_grade_levels_column')]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(model_name='course', name='subject_type'),
                migrations.AddField(
                    model_name='course',
                    name='subject_type_stored',
                    field=models.CharField(
                        db_column='subject_type',
                        max_length=20,
                        choices=[
                            ('math', 'Math'),
                            ('science', 'Science'),
                            ('humanities', 'Humanities'),
                            ('language', 'Language'),
                            ('other', 'Other'),
                        ],
                        blank=True,
                        default='',
                        help_text=(
                            'Deprecated — read Course.subject_type, which '
                            'maps subject_code.'
                        ),
                    ),
                ),
            ],
        ),
    ]
