# Generated by Django 6.0.2 on 2026-09-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0038_deprecate_course_subject_type_column'),
        ('dashboard', '0027_add_restore_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='shared_materials',
            field=models.ManyToManyField(blank=True, help_text='Platform-wide materials attached to this course by hand, on top of those matched automatically by subject + grade.', related_name='attached_courses', to='dashboard.teachingmaterialupload'),
        ),
    ]
