# Generated by Django 6.0.2 on 2026-09-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0040_remove_course_shared_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='retired_at',
            field=models.DateTimeField(blank=True, help_text='When this unit was parked. Null = live.', null=True),
        ),
    ]
