# Generated by Django 6.0.2 on 2026-04-29 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0018_feedback_screenshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpAssistantConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('super_admin', 'Super Admin')], default='student', help_text='Resolved at conversation start; drives tool catalog filtering.', max_length=15)),
                ('page_url_at_start', models.CharField(blank=True, default='', max_length=500)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpAssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool_result', 'Tool Result')], max_length=15)),
                ('content', models.TextField(blank=True, default='')),
                ('citations', models.JSONField(blank=True, default=list)),
                ('tool_proposals', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.helpassistantconversation')),
                ('escalated_to_feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.feedbackreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpAssistantToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=64)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('confirmed', 'Confirmed (pending execution)'), ('executed', 'Executed'), ('cancelled', 'Cancelled by user'), ('errored', 'Errored'), ('rejected', 'Rejected (permission denied)')], default='proposed', max_length=15)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='support.helpassistantconversation')),
                ('message', models.ForeignKey(help_text='The assistant turn that proposed the call.', on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='support.helpassistantmessage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-proposed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='helpassistantconversation',
            index=models.Index(fields=['user', '-last_message_at'], name='support_hel_user_id_dff94a_idx'),
        ),
        migrations.AddIndex(
            model_name='helpassistantmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='support_hel_convers_08c631_idx'),
        ),
        migrations.AddIndex(
            model_name='helpassistanttoolcall',
            index=models.Index(fields=['conversation', '-proposed_at'], name='support_hel_convers_b5ebf6_idx'),
        ),
        migrations.AddIndex(
            model_name='helpassistanttoolcall',
            index=models.Index(fields=['tool_name', '-proposed_at'], name='support_hel_tool_na_f417a2_idx'),
        ),
    ]
