# Generated by Django 6.0.2 on 2026-02-18 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='safetyauditlog',
            new_name='safety_safe_event_t_2186eb_idx',
            old_name='safety_safe_event_t_idx',
        ),
        migrations.RenameIndex(
            model_name='safetyauditlog',
            new_name='safety_safe_user_ha_3aa6c3_idx',
            old_name='safety_safe_user_ha_idx',
        ),
        migrations.RenameIndex(
            model_name='safetyauditlog',
            new_name='safety_safe_severit_5c3d5d_idx',
            old_name='safety_safe_severit_idx',
        ),
    ]
