# Generated by Django 6.0.2 on 2026-05-24 18:05
# Manually edited: added VectorExtension() + HNSW index on Postgres.
# Mirrors curriculum/0029_curriculumchunk.py. See
# memory/pgvector_migration_plan.md (Phase 7 — support KB).

import ai_tutor.apps.curriculum.vector_field
from django.db import migrations, models


# See curriculum/0029_curriculumchunk.py for why VectorExtension() was
# replaced with a vendor-gated RunPython.
def _enable_vector_extension(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector;")


def _drop_vector_extension(apps, schema_editor):
    return  # no-op; see curriculum/0029 for rationale


_HNSW_INDEX_NAME = 'support_chunk_embedding_hnsw'
_CREATE_HNSW_SQL = (
    f"CREATE INDEX IF NOT EXISTS {_HNSW_INDEX_NAME} "
    f"ON support_supportchunk "
    f"USING hnsw (embedding vector_cosine_ops) "
    f"WITH (m = 16, ef_construction = 64);"
)
_DROP_HNSW_SQL = f"DROP INDEX IF EXISTS {_HNSW_INDEX_NAME};"


def _add_hnsw(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(_CREATE_HNSW_SQL)


def _drop_hnsw(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(_DROP_HNSW_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        # ``CREATE EXTENSION IF NOT EXISTS vector;`` on Postgres; no-op
        # on SQLite. See top-of-file for the VectorExtension replacement.
        migrations.RunPython(_enable_vector_extension, _drop_vector_extension),
        migrations.CreateModel(
            name='SupportChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('embedding', ai_tutor.apps.curriculum.vector_field.VectorField(dimensions=384, help_text='sentence-transformers all-MiniLM-L6-v2 vector. text column on SQLite.')),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('source', models.CharField(blank=True, default='', help_text='help_faq / admin_guide / dashboard / etc.', max_length=64)),
                ('section_title', models.CharField(blank=True, default='', max_length=200)),
                ('audience', models.CharField(default='all', help_text="'all' (visible to students + teachers) or 'staff' (teachers + super_admins only).", max_length=32)),
                ('anchor', models.CharField(blank=True, default='', max_length=200)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'audience'], name='supportchunk_src_aud_idx')],
            },
        ),
        migrations.RunPython(_add_hnsw, _drop_hnsw),
    ]
