#!/usr/bin/env python
"""Regenerate the per-language contents rails for the playbook.

The English rail comes from ``_index.py``, generated from the .docx alongside
the prose. Translated prose has no .docx behind it — the section files are the
source — so the rail for a translated section is derived from the file itself.

Without this, a Portuguese reader gets Portuguese prose under an English
contents list, which looks like a half-finished translation even though the
page is complete.

    python scripts/build_playbook_translations.py

Writes ``ai_tutor/apps/docs/_index_i18n.py``. Anchors are taken verbatim, so a
translated heading MUST keep the English ``id`` — that is what the rail links
to, and what any inbound deep link already points at.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

PACKAGE = Path(__file__).resolve().parent.parent / 'ai_tutor'
SECTIONS = PACKAGE / 'templates' / 'docs' / 'sections'
OUT = PACKAGE / 'apps' / 'docs' / '_index_i18n.py'

# <h2 id="anchor">Text</h2> — the same shape build_playbook_docs.py emits.
_H2 = re.compile(r'<h2\s+id="([^"]+)"\s*>(.*?)</h2>', re.DOTALL | re.IGNORECASE)
_TAGS = re.compile(r'<[^>]+>')
_ENTITIES = {'&amp;': '&', '&lt;': '<', '&gt;': '>', '&#x27;': "'",
             '&quot;': '"', '&nbsp;': ' '}


def _plain(html: str) -> str:
    text = _TAGS.sub('', html)
    for entity, char in _ENTITIES.items():
        text = text.replace(entity, char)
    return ' '.join(text.split())


def scan() -> dict[str, dict[str, list[tuple[str, str]]]]:
    out: dict[str, dict[str, list[tuple[str, str]]]] = {}
    for lang_dir in sorted(p for p in SECTIONS.iterdir() if p.is_dir()):
        lang = lang_dir.name
        per_slug: dict[str, list[tuple[str, str]]] = {}
        for page in sorted(lang_dir.glob('*.html')):
            headings = [(anchor, _plain(title))
                        for anchor, title in _H2.findall(page.read_text())]
            if headings:
                per_slug[page.stem] = headings
        if per_slug:
            out[lang] = per_slug
    return out


def render(data) -> str:
    lines = [
        '"""Generated by scripts/build_playbook_translations.py — do not edit.',
        '',
        'The contents rail for each TRANSLATED section, keyed by language then',
        'slug. The English rail lives in _index.py; this is its counterpart for',
        'the languages whose prose has been translated.',
        '',
        'Anchors are the English ones by construction — a translated heading',
        'keeps the id it was generated with, so every rail link and every',
        'inbound deep link still resolves.',
        '"""',
        '',
        'HEADINGS_BY_LANGUAGE = {',
    ]
    for lang, per_slug in sorted(data.items()):
        lines.append(f'    {lang!r}: {{')
        for slug, headings in sorted(per_slug.items()):
            lines.append(f'        {slug!r}: [')
            for anchor, title in headings:
                lines.append(f'            ({anchor!r}, {title!r}),')
            lines.append('        ],')
        lines.append('    },')
    lines.append('}')
    return '\n'.join(lines) + '\n'


def main() -> int:
    data = scan()
    OUT.write_text(render(data))
    total = sum(len(v) for v in data.values())
    langs = ', '.join(sorted(data)) or '(none)'
    print(f'{OUT.relative_to(PACKAGE.parent)}: {total} section(s) across {langs}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
