# Generated by Django 6.0.2 on 2026-02-12 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Default Claude'", max_length=100)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT)'), ('azure_openai', 'Azure OpenAI'), ('local_ollama', 'Local (Ollama)')], default='anthropic', max_length=20)),
                ('model_name', models.CharField(default='claude-sonnet-4-20250514', help_text="Model identifier (e.g., 'claude-sonnet-4-20250514', 'gpt-4o')", max_length=100)),
                ('api_base', models.URLField(blank=True, help_text='Custom API endpoint (for Azure, Ollama, etc.)', null=True)),
                ('api_key_env_var', models.CharField(default='ANTHROPIC_API_KEY', help_text='Environment variable name containing the API key', max_length=100)),
                ('max_tokens', models.PositiveIntegerField(default=1024)),
                ('temperature', models.FloatField(default=0.7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_configs', to='accounts.institution')),
            ],
            options={
                'verbose_name': 'Model Configuration',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Friendly K-5 Tutor'", max_length=100)),
                ('system_prompt', models.TextField(help_text='Core persona and role definition')),
                ('teaching_style_prompt', models.TextField(blank=True, help_text='Teaching methodology (Socratic, direct instruction, etc.)')),
                ('safety_prompt', models.TextField(blank=True, help_text='Content restrictions and safety guidelines')),
                ('format_rules_prompt', models.TextField(blank=True, help_text='Output formatting rules (length, structure, etc.)')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_packs', to='accounts.institution')),
            ],
            options={
                'ordering': ['-is_active', '-updated_at'],
                'unique_together': {('institution', 'name', 'version')},
            },
        ),
    ]
