# Generated by Django 6.0.2 on 2026-02-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptpack',
            name='content_generation_prompt',
            field=models.TextField(blank=True, default='', help_text='System prompt for lesson content generation.'),
        ),
        migrations.AddField(
            model_name='promptpack',
            name='exit_ticket_prompt',
            field=models.TextField(blank=True, default='', help_text='System prompt for exit ticket generation.'),
        ),
        migrations.AddField(
            model_name='promptpack',
            name='grading_prompt',
            field=models.TextField(blank=True, default='', help_text='System prompt for answer grading.'),
        ),
        migrations.AddField(
            model_name='promptpack',
            name='image_generation_prompt',
            field=models.TextField(blank=True, default='', help_text='Prefix/context for image generation prompts (style, safety, educational context).'),
        ),
        migrations.AddField(
            model_name='promptpack',
            name='tutor_system_prompt',
            field=models.TextField(blank=True, default='', help_text='Full tutor system prompt override. Supports {institution_name}, {locale_context}, {tutor_name}, {language}, {grade_level}, {safety_prompt} placeholders.'),
        ),
    ]
