# Generated by Django 6.0.2 on 2026-02-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_add_purpose_to_modelconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='purpose',
            field=models.CharField(choices=[('generation', 'Content Generation (Curriculum, Lessons)'), ('tutoring', 'Student Tutoring'), ('exit_tickets', 'Exit Ticket Generation'), ('skill_extraction', 'Skill Extraction')], default='generation', max_length=20),
        ),
    ]
