# Generated by Django 6.0.2 on 2026-02-26 15:04

from django.db import migrations


def switch_generation_to_haiku(apps, schema_editor):
    """Switch generation-purpose ModelConfigs from Sonnet to Haiku for rate limit headroom."""
    ModelConfig = apps.get_model('llm', 'ModelConfig')
    updated = ModelConfig.objects.filter(
        purpose='generation',
        model_name__icontains='sonnet',
    ).update(model_name='claude-haiku-4-5-20251001')
    if updated:
        print(f"  Switched {updated} generation config(s) to claude-haiku-4-5-20251001")


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0005_add_exit_tickets_skill_extraction_purposes'),
    ]

    operations = [
        migrations.RunPython(switch_generation_to_haiku, migrations.RunPython.noop),
    ]
