# Generated by Django 6.0.2 on 2026-02-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0006_switch_generation_configs_to_haiku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='model_name',
            field=models.CharField(default='claude-haiku-4-5-20251001', help_text="Model identifier (e.g., 'claude-haiku-4-5-20251001', 'claude-sonnet-4-20250514', 'gpt-4o')", max_length=100),
        ),
    ]
