# Generated by Django 6.0.2 on 2026-05-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0019_seed_regen_config_and_lower_tutor_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='purpose',
            field=models.CharField(choices=[('generation', 'Content Generation (Curriculum, Lessons)'), ('tutoring', 'Student Tutoring'), ('exit_tickets', 'Exit Ticket Generation'), ('skill_extraction', 'Skill Extraction'), ('image_generation', 'Image Generation'), ('help_assistant', 'In-app Help Assistant'), ('judge', 'Post-response Judge'), ('regen', 'Tutor Response Regeneration'), ('student_sim', 'Synthetic Student (Simulator)')], default='generation', max_length=20),
        ),
    ]
