# Generated by Django 6.0.2 on 2026-05-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0031_partial_rollback_tutoring_to_opus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelconfig',
            name='purpose',
            field=models.CharField(choices=[('generation', 'Content Generation (Curriculum, Lessons)'), ('tutoring', 'Student Tutoring'), ('exit_tickets', 'Exit Ticket Generation'), ('skill_extraction', 'Skill Extraction'), ('image_generation', 'Image Generation'), ('help_assistant', 'In-app Help Assistant'), ('judge', 'Post-response Judge'), ('judge_fallback', 'Post-response Judge — Tier 2 Fallback'), ('judge_fallback_2', 'Post-response Judge — Tier 3 Fallback'), ('regen', 'Tutor Response Regeneration'), ('student_sim', 'Synthetic Student (Simulator)'), ('content_judge_image_prompt', 'Content Judge — Image Prompt (PRE-gen)'), ('content_judge_factual_step', 'Content Judge — Factual (Lesson Step)'), ('content_judge_figure_alignment', 'Content Judge — Figure Alignment (POST-gen vision)'), ('content_judge_exit_question', 'Content Judge — Exit Ticket Question (MCQ)'), ('content_judge_pedagogy_step', 'Content Judge — Pedagogical Soundness (Lesson Step)'), ('content_judge_safety_content', 'Content Judge — Safety + Cultural Fit (Content)'), ('grader_math', 'v2 Grader — Math Path'), ('grader_grounded', 'v2 Grader — Grounded (KB + Google) — Gemini-pinned'), ('tutor_move', 'v2 StudentTutor — Per-Move Response'), ('conformance_classifier', 'v2 Conformance Classifier'), ('tutor_claim_adjudicator', 'v2 Tutor-Claim Adjudicator — Gemini-pinned'), ('profiler_summary', 'v2 StudentProfiler — End-of-Session Summary')], default='generation', max_length=40),
        ),
    ]
