# Generated by Django 6.0.2 on 2026-02-12 03:36

import apps.media_library.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('pdf', 'PDF Document')], max_length=10)),
                ('file', models.FileField(upload_to=apps.media_library.models.media_upload_path)),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility text for images', max_length=300)),
                ('caption', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for search', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='accounts.institution')),
            ],
            options={
                'verbose_name': 'Media Asset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('top', 'Above content'), ('inline', 'Inline with content'), ('side', 'Side panel')], default='top', max_length=10)),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Order when multiple media attached to same step')),
                ('lesson_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_attachments', to='curriculum.lessonstep')),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_usages', to='media_library.mediaasset')),
            ],
            options={
                'verbose_name': 'Step Media Attachment',
                'ordering': ['order_index'],
            },
        ),
    ]
