# Generated by Django 6.0.2 on 2026-05-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_remove_stepmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='figure_facts',
            field=models.JSONField(blank=True, help_text='Structured visual facts extracted from this figure: scene_description, labelled_features, angle_relationships, extra_facts, anchor_prompts. See apps.curriculum.figure_facts_schema.FigureFacts.', null=True),
        ),
    ]
