# Generated by Django 6.0.2 on 2026-05-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0003_mediaasset_figure_facts'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='judge_outputs',
            field=models.JSONField(blank=True, default=dict, help_text='Content-judge verdicts keyed by judge name (figure_alignment, ...)'),
        ),
    ]
